import type { FirstGlowAttentionTrigger } from "./first-glow-attention.js";

export const FIRST_GLOW_HISTORY_SCHEMA_VERSION = 1 as const;

export interface FirstGlowResourceEffect { kind: string; amount: number; reason: string; }
export interface FirstGlowMovementRecord { id: string; tick: number; sparkId: string; eventId: string; cells: { x: number; y: number }[]; routeRevision: number; movementCost: number; resourceEffects: FirstGlowResourceEffect[]; resultingEventId: string; }
export interface FirstGlowDecisionUsage { requestId: string; outcome: "rules-only" | "recorded" | "fallback" | "historical-replay"; reservedUnits: number; usedUnits: number; }
export interface FirstGlowDecisionRecord { id: string; tick: number; sparkId: string; eventId: string; trigger: FirstGlowAttentionTrigger | "ordinary-rules-only"; candidates: string[]; selectedAlternative?: string; source: "rules" | "ai"; providerId?: string; profileVersion: number; evidenceEventIds: string[]; contextHash: string; validation: "valid" | "invalid"; fallbackReason?: string; latencyMs: number; usage: FirstGlowDecisionUsage; resultingEventId: string; }
export interface FirstGlowHistory { schemaVersion: typeof FIRST_GLOW_HISTORY_SCHEMA_VERSION; movements: FirstGlowMovementRecord[]; decisions: FirstGlowDecisionRecord[]; }

const compare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
const sortedUnique = (values: string[]) => [...new Set(values)].sort(compare);
export function createFirstGlowHistory(): FirstGlowHistory { return { schemaVersion: FIRST_GLOW_HISTORY_SCHEMA_VERSION, movements: [], decisions: [] }; }
export function appendFirstGlowMovement(history: FirstGlowHistory, movement: FirstGlowMovementRecord): void { if (!history.movements.some(item => item.id === movement.id)) history.movements.push(structuredClone(movement)); history.movements.sort((left, right) => left.tick - right.tick || compare(left.id, right.id)); }
export function appendFirstGlowDecision(history: FirstGlowHistory, decision: FirstGlowDecisionRecord): void { if (!history.decisions.some(item => item.id === decision.id)) history.decisions.push(structuredClone({ ...decision, candidates: sortedUnique(decision.candidates), evidenceEventIds: sortedUnique(decision.evidenceEventIds) })); history.decisions.sort((left, right) => left.tick - right.tick || compare(left.id, right.id)); }
export function validateFirstGlowHistory(history: FirstGlowHistory, sparkIds: string[]): void { if (history.schemaVersion !== FIRST_GLOW_HISTORY_SCHEMA_VERSION || !Array.isArray(history.movements) || !Array.isArray(history.decisions)) throw new Error("unsupported First Glow history version"); const sparks = new Set(sparkIds); const ids = new Set<string>(); for (const movement of history.movements) { if (!movement.id || ids.has(movement.id) || !Number.isInteger(movement.tick) || movement.tick < 0 || !sparks.has(movement.sparkId) || !movement.eventId || !movement.resultingEventId || !Number.isInteger(movement.routeRevision) || movement.routeRevision < 0 || !Number.isInteger(movement.movementCost) || movement.movementCost < 0 || !movement.cells.length || !movement.resourceEffects.every(effect => Number.isInteger(effect.amount))) throw new Error(`invalid First Glow movement record ${movement.id}`); ids.add(movement.id); } for (const decision of history.decisions) { if (!decision.id || ids.has(decision.id) || !Number.isInteger(decision.tick) || decision.tick < 0 || !sparks.has(decision.sparkId) || !decision.eventId || !decision.resultingEventId || !decision.candidates.length || !Number.isInteger(decision.profileVersion) || decision.profileVersion < 1 || !decision.contextHash || !["valid", "invalid"].includes(decision.validation) || !Number.isInteger(decision.latencyMs) || decision.latencyMs < 0 || !Number.isInteger(decision.usage.reservedUnits) || !Number.isInteger(decision.usage.usedUnits)) throw new Error(`invalid First Glow decision record ${decision.id}`); ids.add(decision.id); } }
