import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { bundleHash, decodeWorldBundle } from "@mimir/world-data";
import { createFirstGlowState, validateFirstGlowState } from "./structured.js";
import { advanceFirstGlow } from "./first-glow-actions.js";

const bundle = decodeWorldBundle(JSON.parse(readFileSync(fileURLToPath(new URL("../../../assets/world/generated/sha256-92cc5cee6d8859375c046057ef6341fa6844cf6cbe610177d1d81726af0decf3/world.json", import.meta.url)), "utf8")));
if (bundle.schemaVersion !== 3) throw new Error("T3 fixture is not schema 3");
test("share-charge transfers only between co-present Sparks and records consumption/need", () => { const state = createFirstGlowState(bundle, "first-glow-region", "Opening region", 2); const first = state.settlements[0].sparks[0]; const second = state.settlements[0].sparks[1]; second.position = { ...first.position }; first.intendedActivity = "share-charge"; first.carriedCharge = 3; const next = advanceFirstGlow(state); assert.equal(next.settlements[0].sparks[0].carriedCharge, 1); assert.equal(next.settlements[0].sparks[1].carriedCharge, 0); assert.equal(next.ledger.find(entry => entry.kind === "share")?.amount, 1); assert.equal(next.ledger.some(entry => entry.kind === "consumption" || entry.reason === "charge-deficit"), true); });
test("named external charge inputs conserve the ledger across intake, loss, and consumption", () => { const state = createFirstGlowState(bundle); const spark = state.settlements[0].sparks[0]; spark.carriedCharge = 2; const before = state.settlements[0].sourceCharge + state.settlements[0].communalCharge + spark.carriedCharge; const next = advanceFirstGlow(state, { sourceCharge: 3, communalCharge: 2, loss: 1 }); const after = next.settlements[0].sourceCharge + next.settlements[0].communalCharge + next.settlements[0].sparks[0].carriedCharge; const produced = next.ledger.filter(entry => entry.kind === "production").reduce((total, entry) => total + entry.amount, 0); const lost = next.ledger.filter(entry => entry.kind === "loss").reduce((total, entry) => total + entry.amount, 0); const consumed = next.ledger.filter(entry => entry.kind === "consumption").reduce((total, entry) => total + entry.amount, 0); assert.equal(after, before + produced - lost - consumed); });
test("the conservation matrix clamps loss and rejects invalid named inputs", () => { const state = createFirstGlowState(bundle, "first-glow-region", "Opening region", 4); const initial = state.settlements[0].sourceCharge + state.settlements[0].communalCharge; const next = advanceFirstGlow(state, { sourceCharge: 5, communalCharge: 7, loss: initial + 100 }); const settlement = next.settlements[0]; assert.equal(settlement.sourceCharge + settlement.communalCharge, 0); assert.equal(next.ledger.find(entry => entry.kind === "loss")?.amount, initial + 12); assert.throws(() => advanceFirstGlow(state, { sourceCharge: -1 }), /non-negative integers/); assert.throws(() => advanceFirstGlow(state, { communalCharge: 1.5 }), /non-negative integers/); });
test("twelve Sparks remain deterministic across a full action run", () => { const run = () => { let state = createFirstGlowState(bundle, "first-glow-region", "Opening region", 12); for (let tick = 0; tick < 120; tick += 1) state = advanceFirstGlow(state, { sourceCharge: tick % 9 === 0 ? 1 : 0, communalCharge: tick % 13 === 0 ? 2 : 0, loss: tick % 17 === 0 ? 1 : 0 }); return state; }; assert.deepEqual(run(), run()); });
test("meet requires co-presence at one contact and preserves private evidence", () => { const meetBundle = structuredClone(bundle); const definition = meetBundle.objectDefinitions["light-mark"]; definition.capacity = 2; definition.slots = [definition.slots[0], { id: "contact", offset: { ...definition.slots[0].offset }, capacity: 1 }]; meetBundle.bundle.contentHash = bundleHash(meetBundle); const state = createFirstGlowState(meetBundle, "first-glow-region", "Opening region", 2); const object = meetBundle.objects.find(candidate => candidate.definitionId === "light-mark")!; const contact = { x: object.origin.x + definition.slots[0].offset.x, y: object.origin.y + definition.slots[0].offset.y }; const [first, second] = state.settlements[0].sparks; for (const spark of [first, second]) { spark.intendedActivity = "meet"; spark.status = "interacting"; spark.position = { ...contact }; spark.destinationObjectId = object.id; } first.destinationSlotId = "mark"; second.destinationSlotId = "contact"; state.settlements[0].runtime.reservations = [{ actorId: first.id, objectId: object.id, slotId: "mark" }, { actorId: second.id, objectId: object.id, slotId: "contact" }]; const next = advanceFirstGlow(state); const encounter = next.events.find(event => event.kind === "meet"); assert.ok(encounter); assert.deepEqual(encounter?.participants, ["spark-1", "spark-2"]); assert.equal(encounter?.source, "rules"); assert.equal(next.settlements[0].sparks[0].knownEvidenceEventIds.includes(encounter!.id), true); assert.equal(next.settlements[0].sparks[1].knownEvidenceEventIds.includes(encounter!.id), true); });
test("persisted charge state round-trips across the intake and loss matrix", () => { const inputs = [{ sourceCharge: 0, communalCharge: 0, loss: 0 }, { sourceCharge: 5, communalCharge: 3, loss: 2 }, { sourceCharge: 1, communalCharge: 9, loss: 100 }]; for (const input of inputs) { const state = createFirstGlowState(bundle); state.settlements[0].sparks[0].carriedCharge = 4; const before = state.settlements[0].sourceCharge + state.settlements[0].communalCharge + state.settlements[0].sparks[0].carriedCharge; const next = advanceFirstGlow(state, input); const reloaded = JSON.parse(JSON.stringify(next)) as typeof next; validateFirstGlowState(reloaded); const after = reloaded.settlements[0].sourceCharge + reloaded.settlements[0].communalCharge + reloaded.settlements[0].sparks[0].carriedCharge; const produced = reloaded.ledger.filter(entry => entry.kind === "production").reduce((total, entry) => total + entry.amount, 0); const lost = reloaded.ledger.filter(entry => entry.kind === "loss").reduce((total, entry) => total + entry.amount, 0); const consumed = reloaded.ledger.filter(entry => entry.kind === "consumption").reduce((total, entry) => total + entry.amount, 0); assert.equal(after, before + produced - lost - consumed); assert.deepEqual(advanceFirstGlow(reloaded), advanceFirstGlow(next)); } });
