import { canTraverse, queryCell, validateRuntimeState, validateWorldBundle, type Cell, type DecodedWorldBundle, type FirstGlowActivity, type FirstGlowWorldBundle, type Reservation, type WorldBundle, type WorldRuntimeState } from "@mimir/world-data";

export const STRUCTURED_SIMULATION_VERSION = "mimir-sim-v2" as const;
export type StructuredStatus = "choosing" | "traveling" | "waiting" | "interacting" | "idle";
export type StructuredActivity = "rest" | "collect" | "share" | "craft" | "meet" | "work" | "gather";
export interface StructuredActor { id: string; name: string; position: Cell; status: StructuredStatus; intendedActivity: StructuredActivity; destinationObjectId?: string; destinationSlotId?: string; remainingRoute: Cell[]; remainingCost: number; plannedNavigationRevision: number; committedCells: Cell[]; food: number; hunger: number; waitReason?: string; }
export interface StructuredSettlement { id: string; name: string; bundle: WorldBundle; runtime: WorldRuntimeState; actors: StructuredActor[]; storeFood: number; }
export interface LedgerEntry { kind: "production" | "collection" | "draw" | "share" | "consumption" | "loss" | "idle" | "adjustment"; actorId?: string; amount: number; reason: string; }
export interface StructuredEvent { id: string; kind: "movement" | "arrival" | "collection" | "draw" | "share" | "idle" | "wait" | "explore" | "mark-trace" | "shape-pattern" | "meet"; actorId: string; message: string; cells?: Cell[]; participants?: string[]; evidenceEventIds?: string[]; source?: "rules" | "spontaneous"; }
export interface StructuredState { schemaVersion: 2; spatialModel: "structured-v2"; simulationVersion: typeof STRUCTURED_SIMULATION_VERSION; tick: number; settlements: StructuredSettlement[]; ledger: LedgerEntry[]; events: StructuredEvent[]; }
export const FIRST_GLOW_SIMULATION_VERSION = "mimir-sim-v3-first-glow" as const;
export interface FirstGlowSpark { id: string; name: string; position: Cell; status: StructuredStatus; intendedActivity: FirstGlowActivity; destinationObjectId?: string; destinationSlotId?: string; remainingRoute: Cell[]; remainingCost: number; plannedNavigationRevision: number; committedCells: Cell[]; carriedCharge: number; chargeDeficit: number; readiness: number; knownEvidenceEventIds: string[]; waitReason?: string; }
export interface FirstGlowSettlement { id: string; name: string; bundle: FirstGlowWorldBundle; runtime: WorldRuntimeState; sparks: FirstGlowSpark[]; sourceCharge: number; communalCharge: number; }
export interface FirstGlowState { schemaVersion: 3; spatialModel: "structured-v2"; simulationVersion: typeof FIRST_GLOW_SIMULATION_VERSION; themeId: "living-circuit"; ageId: "first-glow"; tick: number; settlements: FirstGlowSettlement[]; ledger: LedgerEntry[]; events: StructuredEvent[]; }

const compare = (a: string, b: string) => a < b ? -1 : a > b ? 1 : 0;
const key = (cell: Cell) => `${cell.x},${cell.y}`;
function neighbors(cell: Cell): Cell[] { return [{ x: cell.x, y: cell.y - 1 }, { x: cell.x - 1, y: cell.y }, { x: cell.x + 1, y: cell.y }, { x: cell.x, y: cell.y + 1 }]; }
function distance(a: Cell, b: Cell) { return Math.abs(a.x - b.x) + Math.abs(a.y - b.y); }
function route(bundle: DecodedWorldBundle, runtime: WorldRuntimeState, start: Cell, goal: Cell): Cell[] | null {
  const first = queryCell(bundle, runtime, start); const last = queryCell(bundle, runtime, goal); if (!first.walkable || !last.walkable) return null; const open = [start]; const came = new Map<string, Cell>(); const score = new Map([[key(start), 0]]); const estimate = new Map([[key(start), distance(start, goal)]]);
  while (open.length) { open.sort((a, b) => estimate.get(key(a))! - estimate.get(key(b))! || compare(key(a), key(b))); const current = open.shift()!; if (key(current) === key(goal)) { const result = [current]; while (came.has(key(result[0]))) result.unshift(came.get(key(result[0]))!); return result; } for (const next of neighbors(current)) { const edge = canTraverse(bundle, runtime, current, next); if (!edge.walkable) continue; const nextKey = key(next); const nextScore = score.get(key(current))! + edge.cost; if (nextScore >= (score.get(nextKey) ?? Infinity)) continue; came.set(nextKey, current); score.set(nextKey, nextScore); estimate.set(nextKey, nextScore + distance(next, goal)); if (!open.some(cell => key(cell) === nextKey)) open.push(next); } } return null;
}
function slotCell(bundle: WorldBundle, objectId: string, slotId: string): Cell | null { const object = bundle.objects.find(candidate => candidate.id === objectId); if (!object) return null; const definition = bundle.objectDefinitions[object.definitionId]; const slot = definition.slots.find(candidate => candidate.id === slotId); return slot ? { x: object.origin.x + slot.offset.x, y: object.origin.y + slot.offset.y } : null; }
function candidates(settlement: StructuredSettlement, actor: StructuredActor): { objectId: string; slotId: string; cell: Cell; route: Cell[]; cost: number }[] {
  const reserved = new Set(settlement.runtime.reservations.filter(reservation => reservation.actorId !== actor.id).map(reservation => `${reservation.objectId}:${reservation.slotId}`)); const results: { objectId: string; slotId: string; cell: Cell; route: Cell[]; cost: number }[] = [];
  for (const object of settlement.bundle.objects.slice().sort((a, b) => compare(a.id, b.id))) { const definition = settlement.bundle.objectDefinitions[object.definitionId]; if (!definition.capabilities.includes(actor.intendedActivity)) continue; for (const slot of definition.slots.slice().sort((a, b) => compare(a.id, b.id))) { if (reserved.has(`${object.id}:${slot.id}`)) continue; const cell = slotCell(settlement.bundle, object.id, slot.id); if (!cell) continue; const path = route(settlement.bundle, settlement.runtime, actor.position, cell); if (!path) continue; let cost = 0; for (let index = 1; index < path.length; index += 1) { const edge = canTraverse(settlement.bundle, settlement.runtime, path[index - 1], path[index]); if (!edge.walkable) { cost = Infinity; break; } cost += edge.cost; } if (Number.isFinite(cost)) results.push({ objectId: object.id, slotId: slot.id, cell, route: path, cost }); } }
  return results.sort((a, b) => a.cost - b.cost || compare(a.objectId, b.objectId) || compare(a.slotId, b.slotId));
}
function reserve(settlement: StructuredSettlement, actor: StructuredActor): { kind: "reserved"; choice: ReturnType<typeof candidates>[number] } | { kind: "no-free-slot" | "no-route" } {
  const choices = candidates(settlement, actor); if (choices.length) { const choice = choices[0]; settlement.runtime.reservations.push({ actorId: actor.id, objectId: choice.objectId, slotId: choice.slotId }); return { kind: "reserved", choice }; }
  const eligible = settlement.bundle.objects.some(object => settlement.bundle.objectDefinitions[object.definitionId].capabilities.includes(actor.intendedActivity)); if (!eligible) return { kind: "no-route" }; const reserved = new Set(settlement.runtime.reservations.map(item => `${item.objectId}:${item.slotId}`)); const hasFree = settlement.bundle.objects.some(object => settlement.bundle.objectDefinitions[object.definitionId].capabilities.includes(actor.intendedActivity) && settlement.bundle.objectDefinitions[object.definitionId].slots.some(slot => !reserved.has(`${object.id}:${slot.id}`))); return hasFree ? { kind: "no-route" } : { kind: "no-free-slot" };
}
function release(settlement: StructuredSettlement, actorId: string) { settlement.runtime.reservations = settlement.runtime.reservations.filter(reservation => reservation.actorId !== actorId); }

export function validateStructuredState(state: StructuredState): void { if (state.schemaVersion !== 2 || state.spatialModel !== "structured-v2" || state.simulationVersion !== STRUCTURED_SIMULATION_VERSION) throw new Error("unsupported structured state version"); for (const settlement of state.settlements) { validateWorldBundle(settlement.bundle); validateRuntimeState(settlement.bundle, settlement.runtime); const ids = new Set<string>(); for (const actor of settlement.actors) { if (ids.has(actor.id)) throw new Error(`duplicate actor ${actor.id}`); ids.add(actor.id); if (!Number.isInteger(actor.position.x) || !Number.isInteger(actor.position.y)) throw new Error(`invalid actor position ${actor.id}`); } } }

export function validateFirstGlowState(state: FirstGlowState): void { if (state.schemaVersion !== 3 || state.spatialModel !== "structured-v2" || state.simulationVersion !== FIRST_GLOW_SIMULATION_VERSION || state.themeId !== "living-circuit" || state.ageId !== "first-glow") throw new Error("unsupported First Glow state version"); for (const settlement of state.settlements) { validateWorldBundle(settlement.bundle); validateRuntimeState(settlement.bundle, settlement.runtime, settlement.sparks.map(spark => spark.id)); const ids = new Set<string>(); for (const spark of settlement.sparks) { if (ids.has(spark.id)) throw new Error(`duplicate Spark ${spark.id}`); ids.add(spark.id); if (!Number.isInteger(spark.position.x) || !Number.isInteger(spark.position.y)) throw new Error(`invalid Spark position ${spark.id}`); if (!Number.isInteger(spark.carriedCharge) || spark.carriedCharge < 0 || !Number.isInteger(spark.chargeDeficit) || spark.chargeDeficit < 0 || !Number.isInteger(spark.readiness) || spark.readiness < 0 || spark.readiness > 100) throw new Error(`invalid First Glow resources for ${spark.id}`); } } }

export function createFirstGlowState(bundle: FirstGlowWorldBundle, settlementId = "first-glow-region", settlementName = "Opening region", sparkCount = 1): FirstGlowState { validateWorldBundle(bundle); const spawns = bundle.spawns.filter(spawn => spawn.settlementId === settlementId); if (!spawns.length) throw new Error(`no First Glow spawn for settlement ${settlementId}`); const sparks = Array.from({ length: sparkCount }, (_, index): FirstGlowSpark => { const spawn = spawns[index % spawns.length]; return { id: `spark-${index + 1}`, name: `Spark ${index + 1}`, position: { ...spawn.cell }, status: "choosing", intendedActivity: "seek-charge", remainingRoute: [], remainingCost: 0, plannedNavigationRevision: 0, committedCells: [{ ...spawn.cell }], carriedCharge: 0, chargeDeficit: 0, readiness: 100, knownEvidenceEventIds: [] }; }); const state: FirstGlowState = { schemaVersion: 3, spatialModel: "structured-v2", simulationVersion: FIRST_GLOW_SIMULATION_VERSION, themeId: "living-circuit", ageId: "first-glow", tick: 0, settlements: [{ id: settlementId, name: settlementName, bundle, runtime: { navigationRevision: 0, objects: [], reservations: [] }, sparks, sourceCharge: 24, communalCharge: 0 }], ledger: [], events: [] }; validateFirstGlowState(state); return state; }

const firstGlowCapability = (activity: FirstGlowActivity) => activity === "seek-charge" || activity === "draw-charge" ? "charge-pool" : activity === "seek-shelter" || activity === "idle" ? "shelter-niche" : activity === "explore" ? "trace" : activity === "shape-pattern" ? "pattern-shard" : activity === "mark-trace" || activity === "meet" ? "light-mark" : null;
function firstGlowSlotCell(bundle: FirstGlowWorldBundle, objectId: string, slotId: string): Cell | null { const object = bundle.objects.find(candidate => candidate.id === objectId); if (!object) return null; const slot = bundle.objectDefinitions[object.definitionId].slots.find(candidate => candidate.id === slotId); return slot ? { x: object.origin.x + slot.offset.x, y: object.origin.y + slot.offset.y } : null; }
function firstGlowCandidates(settlement: FirstGlowSettlement, spark: FirstGlowSpark) { const capability = firstGlowCapability(spark.intendedActivity); if (!capability) return []; const reserved = new Set(settlement.runtime.reservations.filter(item => item.actorId !== spark.id).map(item => `${item.objectId}:${item.slotId}`)); return settlement.bundle.objects.flatMap(object => { const definition = settlement.bundle.objectDefinitions[object.definitionId]; if (!definition.capabilities.includes(capability)) return []; return definition.slots.flatMap(slot => { if (reserved.has(`${object.id}:${slot.id}`)) return []; const target = firstGlowSlotCell(settlement.bundle, object.id, slot.id); if (!target) return []; const path = route(settlement.bundle, settlement.runtime, spark.position, target); if (!path) return []; let cost = 0; for (let index = 1; index < path.length; index += 1) { const edge = canTraverse(settlement.bundle, settlement.runtime, path[index - 1], path[index]); if (!edge.walkable) return []; cost += edge.cost; } return [{ objectId: object.id, slotId: slot.id, target, path, cost }]; }); }).sort((a, b) => a.cost - b.cost || compare(a.objectId, b.objectId) || compare(a.slotId, b.slotId)); }
function releaseFirstGlow(settlement: FirstGlowSettlement, sparkId: string) { settlement.runtime.reservations = settlement.runtime.reservations.filter(item => item.actorId !== sparkId); }

export function advanceFirstGlowState(input: FirstGlowState): FirstGlowState { validateFirstGlowState(input); const state = structuredClone(input); state.tick += 1; state.ledger = []; state.events = []; for (const settlement of state.settlements) { for (const spark of settlement.sparks.slice().sort((a, b) => compare(a.id, b.id))) { spark.committedCells = [{ ...spark.position }]; if ((spark.status === "choosing" || spark.status === "waiting" || spark.status === "idle") && !spark.destinationObjectId) { const choices = firstGlowCandidates(settlement, spark); if (!choices.length) { spark.status = "waiting"; spark.waitReason = "no-route-or-free-slot"; state.events.push({ id: `event-${state.tick}-${spark.id}-wait`, kind: "wait", actorId: spark.id, message: `${spark.name} is waiting: no reachable ${spark.intendedActivity} site.` }); continue; } const choice = choices[0]; settlement.runtime.reservations.push({ actorId: spark.id, objectId: choice.objectId, slotId: choice.slotId }); spark.destinationObjectId = choice.objectId; spark.destinationSlotId = choice.slotId; spark.remainingRoute = choice.path.slice(1); spark.remainingCost = 0; spark.plannedNavigationRevision = settlement.runtime.navigationRevision; spark.status = spark.remainingRoute.length ? "traveling" : "interacting"; }
      if (spark.status === "traveling") { if (spark.plannedNavigationRevision !== settlement.runtime.navigationRevision) { const target = spark.destinationObjectId && spark.destinationSlotId ? firstGlowSlotCell(settlement.bundle, spark.destinationObjectId, spark.destinationSlotId) : null; const replanned = target ? route(settlement.bundle, settlement.runtime, spark.position, target) : null; if (!replanned) { spark.status = "waiting"; spark.waitReason = "no-route"; continue; } spark.remainingRoute = replanned.slice(1); spark.remainingCost = 0; spark.plannedNavigationRevision = settlement.runtime.navigationRevision; } let budget = 2; while (budget > 0 && spark.remainingRoute.length) { const next = spark.remainingRoute[0]; const edge = canTraverse(settlement.bundle, settlement.runtime, spark.position, next); if (!edge.walkable) { spark.status = "waiting"; spark.waitReason = edge.reason; break; } if (spark.remainingCost <= 0) spark.remainingCost = edge.cost; const debit = Math.min(budget, spark.remainingCost); spark.remainingCost -= debit; budget -= debit; if (spark.remainingCost === 0) { spark.position = { ...next }; spark.remainingRoute.shift(); spark.committedCells.push({ ...spark.position }); } } if (spark.status === "traveling" && spark.remainingRoute.length === 0) spark.status = "interacting"; if (spark.committedCells.length > 1) state.events.push({ id: `event-${state.tick}-${spark.id}-movement`, kind: "movement", actorId: spark.id, cells: spark.committedCells, message: `${spark.name} moved ${spark.committedCells.length - 1} cell(s).` }); }
      if (spark.status === "interacting") { const reservation = settlement.runtime.reservations.find(item => item.actorId === spark.id); const target = reservation ? firstGlowSlotCell(settlement.bundle, reservation.objectId, reservation.slotId) : null; if (!reservation || !target || key(target) !== key(spark.position)) { releaseFirstGlow(settlement, spark.id); spark.status = "waiting"; spark.waitReason = "invalid-destination"; continue; } if (spark.intendedActivity === "seek-charge" || spark.intendedActivity === "draw-charge") { const amount = Math.min(2, settlement.sourceCharge); settlement.sourceCharge -= amount; spark.carriedCharge += amount; state.ledger.push({ kind: "draw", actorId: spark.id, amount, reason: amount ? "arrived-at-charge-pool" : "empty-charge-pool" }); state.events.push({ id: `event-${state.tick}-${spark.id}-draw`, kind: "draw", actorId: spark.id, message: `${spark.name} drew ${amount} charge.` }); } else if (spark.intendedActivity === "idle" || spark.intendedActivity === "seek-shelter") { const recovered = Math.min(10, 100 - spark.readiness); spark.readiness += recovered; state.ledger.push({ kind: "idle", actorId: spark.id, amount: recovered, reason: "arrived-at-shelter-niche" }); state.events.push({ id: `event-${state.tick}-${spark.id}-idle`, kind: "idle", actorId: spark.id, message: `${spark.name} idled and recovered ${recovered} readiness.` }); } else if (spark.intendedActivity === "meet") { const companion = settlement.sparks.find(candidate => candidate.id > spark.id && candidate.status === "interacting" && candidate.destinationObjectId === reservation.objectId && candidate.position.x === spark.position.x && candidate.position.y === spark.position.y); if (!companion) { releaseFirstGlow(settlement, spark.id); spark.status = "waiting"; spark.waitReason = "no-co-present-spark"; continue; } const eventId = `event-${state.tick}-${spark.id}-meet-${companion.id}`; const event = { id: eventId, kind: "meet" as const, actorId: spark.id, participants: [spark.id, companion.id], evidenceEventIds: [], source: "rules" as const, message: `${spark.name} met ${companion.name} at a shared contact site.` }; state.events.push(event); spark.knownEvidenceEventIds.push(eventId); companion.knownEvidenceEventIds.push(eventId); releaseFirstGlow(settlement, companion.id); companion.status = "choosing"; companion.destinationObjectId = undefined; companion.destinationSlotId = undefined; companion.remainingRoute = []; companion.remainingCost = 0; } releaseFirstGlow(settlement, spark.id); spark.status = "choosing"; spark.destinationObjectId = undefined; spark.destinationSlotId = undefined; spark.remainingRoute = []; spark.remainingCost = 0; } } } validateFirstGlowState(state); return state; }

export function createStructuredState(bundle: WorldBundle, settlementId = "first-village", settlementName = "Hearthmere", actorCount = 12): StructuredState {
  validateWorldBundle(bundle); const spawns = bundle.spawns.filter(spawn => spawn.settlementId === settlementId); if (!spawns.length) throw new Error(`no spawn for settlement ${settlementId}`); const actors = Array.from({ length: actorCount }, (_, index) => { const spawn = spawns[index % spawns.length]; return { id: `villager-${index + 1}`, name: `Villager ${index + 1}`, position: { ...spawn.cell }, status: "choosing" as const, intendedActivity: index % 3 === 0 ? "collect" as const : "rest" as const, remainingRoute: [], remainingCost: 0, plannedNavigationRevision: 0, committedCells: [{ ...spawn.cell }], food: 0, hunger: 0 }; }); const state: StructuredState = { schemaVersion: 2, spatialModel: "structured-v2", simulationVersion: STRUCTURED_SIMULATION_VERSION, tick: 0, settlements: [{ id: settlementId, name: settlementName, bundle, runtime: { navigationRevision: 0, objects: [], reservations: [] }, actors, storeFood: 24 }], ledger: [], events: [] }; validateStructuredState(state); return state;
}

export function advanceStructuredState(input: StructuredState): StructuredState {
  validateStructuredState(input); const state: StructuredState = structuredClone(input); state.tick += 1; state.ledger = []; state.events = []; for (const settlement of state.settlements) { const actors = settlement.actors.slice().sort((a, b) => compare(a.id, b.id)); for (const actor of actors) { actor.committedCells = [{ ...actor.position }]; if (actor.status === "choosing" || actor.status === "idle" || actor.status === "waiting") { if (actor.status === "waiting") actor.waitReason = undefined; if (!actor.destinationObjectId) { const decision = reserve(settlement, actor); if (decision.kind !== "reserved") { actor.status = "waiting"; actor.waitReason = decision.kind; state.events.push({ id: `event-${state.tick}-${actor.id}-wait`, kind: "wait", actorId: actor.id, message: `${actor.id} is waiting: ${decision.kind}.` }); continue; } const { choice } = decision; actor.destinationObjectId = choice.objectId; actor.destinationSlotId = choice.slotId; actor.remainingRoute = choice.route.slice(1); actor.remainingCost = 0; actor.plannedNavigationRevision = settlement.runtime.navigationRevision; actor.status = actor.remainingRoute.length ? "traveling" : "interacting"; } }
      if (actor.status === "traveling") { if (actor.plannedNavigationRevision !== settlement.runtime.navigationRevision) { const target = actor.destinationObjectId && actor.destinationSlotId ? slotCell(settlement.bundle, actor.destinationObjectId, actor.destinationSlotId) : null; const replanned = target ? route(settlement.bundle, settlement.runtime, actor.position, target) : null; if (!replanned) { actor.status = "waiting"; actor.waitReason = "no-route"; continue; } actor.remainingRoute = replanned.slice(1); actor.remainingCost = 0; actor.plannedNavigationRevision = settlement.runtime.navigationRevision; } let budget = 2; while (budget > 0 && actor.remainingRoute.length) { const next = actor.remainingRoute[0]; const edge = canTraverse(settlement.bundle, settlement.runtime, actor.position, next); if (!edge.walkable) { actor.status = "waiting"; actor.waitReason = edge.reason; break; } if (actor.remainingCost <= 0) actor.remainingCost = edge.cost; const debit = Math.min(budget, actor.remainingCost); actor.remainingCost -= debit; budget -= debit; if (actor.remainingCost === 0) { actor.position = { ...next }; actor.remainingRoute.shift(); actor.committedCells.push({ ...actor.position }); } } if (actor.status === "traveling" && actor.remainingRoute.length === 0) actor.status = "interacting"; if (actor.committedCells.length > 1) state.events.push({ id: `event-${state.tick}-${actor.id}-movement`, kind: "movement", actorId: actor.id, cells: actor.committedCells, message: `${actor.id} moved ${actor.committedCells.length - 1} cell(s).` }); }
      if (actor.status === "interacting") { const reservation = settlement.runtime.reservations.find(item => item.actorId === actor.id); const target = reservation?.objectId && reservation.slotId ? slotCell(settlement.bundle, reservation.objectId, reservation.slotId) : null; if (!reservation || !target || key(target) !== key(actor.position)) { release(settlement, actor.id); actor.status = "waiting"; actor.waitReason = "invalid-destination"; continue; } if (actor.intendedActivity === "collect") { const amount = Math.min(2, settlement.storeFood); settlement.storeFood -= amount; actor.food += amount; state.ledger.push({ kind: "collection", actorId: actor.id, amount, reason: "arrived-at-granary" }); state.events.push({ id: `event-${state.tick}-${actor.id}-collection`, kind: "collection", actorId: actor.id, message: `${actor.id} collected ${amount} food.` }); } else if (actor.intendedActivity === "share") { const amount = Math.min(1, actor.food); actor.food -= amount; settlement.storeFood += amount; state.ledger.push({ kind: "share", actorId: actor.id, amount, reason: "arrived-at-granary" }); if (amount) state.events.push({ id: `event-${state.tick}-${actor.id}-share`, kind: "share", actorId: actor.id, message: `${actor.id} shared ${amount} food.` }); } actor.status = "choosing"; release(settlement, actor.id); actor.destinationObjectId = undefined; actor.destinationSlotId = undefined; actor.remainingRoute = []; actor.remainingCost = 0; }
      if (actor.food > 0) { actor.food -= 1; state.ledger.push({ kind: "consumption", actorId: actor.id, amount: 1, reason: "daily-consumption" }); }
    } }
  for (const settlement of state.settlements) { const production = 1; settlement.storeFood += production; state.ledger.push({ kind: "production", amount: production, reason: "global-production" }); }
  validateStructuredState(state); return state;
}
