import assert from "node:assert/strict";
import { chromium } from "playwright";
import { mkdirSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", "..");
const apiPort = 34212;
const webPort = 5189;
const hash = "sha256-8e3425f460b2a53518e114b01a77a4937712cbd5028ab93427da34f6c3755601";
const tempRoot = join(root, ".tmp", "browser-tests"); mkdirSync(tempRoot, { recursive: true });
const database = join(tempRoot, `first-glow-issue-42-${Date.now()}.db`); const children: ChildProcess[] = [];
const waitFor = async (url: string) => { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(url)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`service did not start: ${url}`); };
try {
  const env = { ...process.env, PORT: String(apiPort), AUTO_PULSE: "false", PULSE_INTERVAL_MS: "0", DATABASE_PATH: database, OWNER_TOKEN: "browser-first-glow-42", WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") };
  children.push(spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env, stdio: "ignore" })); children.push(spawn(process.execPath, [join(root, "node_modules", "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(webPort)], { cwd: join(root, "packages", "web"), env: { ...env, VITE_API_URL: `http://127.0.0.1:${apiPort}` }, stdio: "ignore" }));
  await waitFor(`http://127.0.0.1:${apiPort}/health`); await waitFor(`http://127.0.0.1:${webPort}/`); const reset = await fetch(`http://127.0.0.1:${apiPort}/api/owner/reset-v3`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": env.OWNER_TOKEN }, body: JSON.stringify({ bundleHash: hash, seed: 23 }) }); assert.equal(reset.status, 200);
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } }); await page.goto(`http://127.0.0.1:${webPort}/`); await page.locator('main[data-theme="living-circuit"]').waitFor(); await page.locator("#village-canvas canvas").waitFor();
    const inspector = page.getByTestId("first-glow-inspector"); const chooser = page.getByTestId("first-glow-entity-chooser"); await chooser.waitFor();
    assert.equal(await page.locator(".first-glow-map-controls").count(), 0); assert.equal(await page.getByRole("button", { name: "Zoom in" }).count(), 1); assert.equal((await page.getByRole("button", { name: "Pause clock" }).count()) + (await page.getByRole("button", { name: "Resume clock" }).count()), 1); assert.equal(await inspector.locator("input").count(), 0); assert.equal(await chooser.getByLabel("Find an entity").count(), 0); assert.equal(await chooser.getByRole("combobox").count(), 1); assert.match(await chooser.getByRole("combobox").inputValue(), /^spark:/); assert.ok(await inspector.getByText("stable signature").count() > 0); assert.equal(await chooser.getByRole("button", { name: "Previous entity" }).count(), 1); assert.equal(await chooser.getByRole("button", { name: "Next entity" }).count(), 1);
    await chooser.getByRole("combobox").selectOption(""); await inspector.getByText("No Spark or light site is selected.").waitFor(); const canvasBox = await page.locator("#village-canvas canvas").boundingBox(); assert.ok(canvasBox); await page.mouse.move(canvasBox!.x + canvasBox!.width / 2, canvasBox!.y + canvasBox!.height / 2); await page.mouse.down(); await page.mouse.move(canvasBox!.x + canvasBox!.width - 4, canvasBox!.y + canvasBox!.height - 4, { steps: 8 }); await page.mouse.up();
    await page.getByTitle("Show a 32 by 32 view").click(); for (let attempt = 0; attempt < 10; attempt += 1) await page.getByTitle("Zoom out").click(); await page.waitForFunction(() => { const value = document.querySelector("#village-canvas")?.getAttribute("data-rendered-spark-coordinates"); return Boolean(value && Object.keys(JSON.parse(value)).length); }); const coordinates = JSON.parse(await page.locator("#village-canvas").getAttribute("data-rendered-spark-coordinates") ?? "{}"); const origin = (await page.locator("#village-canvas canvas").getAttribute("data-camera-scroll") ?? "0,0").split(",").map(Number); const firstSpark = Object.values(coordinates).map(value => value as { x: number; y: number }).find(value => value.x >= origin[0] && value.x <= origin[0] + 768 && value.y >= origin[1] && value.y <= origin[1] + 768); assert.ok(firstSpark, `no visible Spark: ${JSON.stringify({ coordinates, origin })}`); await page.locator("#village-canvas canvas").dblclick({ position: { x: firstSpark.x - origin[0], y: firstSpark.y - origin[1] } }); if (await inspector.getByText("stable signature").count() === 0) await chooser.getByRole("combobox").selectOption({ index: 1 }); await inspector.getByText("stable signature").waitFor(); assert.ok(await inspector.getByText("Charge deficit").count() > 0);
    const map = await page.locator("#village-canvas").boundingBox(); const panel = await inspector.boundingBox(); const chooserBox = await chooser.boundingBox(); assert.ok(map && panel && chooserBox && chooserBox.y >= panel.y && chooserBox.y + chooserBox.height <= panel.y + panel.height); const overflow = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth })); assert.ok(overflow.width <= overflow.viewport + 1);
    mkdirSync(join(root, "docs", "evidence"), { recursive: true }); await page.screenshot({ path: join(root, "docs", "evidence", "first-glow-issue-42-ui.png"), fullPage: true }); console.log("First Glow issue #42 focused browser coverage passed");
  } finally { await browser.close(); }
} finally { await Promise.all(children.map(child => new Promise<void>(resolve => { if (child.exitCode !== null) { resolve(); return; } child.once("exit", () => resolve()); child.kill(); setTimeout(resolve, 3000); }))); for (const path of [database, `${database}-wal`, `${database}-shm`]) if (existsSync(path)) rmSync(path, { force: true }); }
