import assert from "node:assert/strict";
import { chromium } from "playwright";
import { mkdirSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", ".."); const apiPort = 34231; const webPort = 5208; const hash = "sha256-8e3425f460b2a53518e114b01a77a4937712cbd5028ab93427da34f6c3755601"; const tempRoot = join(root, ".tmp", "browser-tests"); mkdirSync(tempRoot, { recursive: true }); const database = join(tempRoot, `first-glow-live-${Date.now()}.db`); const children: ChildProcess[] = [];
const waitFor = async (url: string) => { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(url)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`service did not start: ${url}`); };
try {
  const env = { ...process.env, PORT: String(apiPort), AUTO_TICK: "false", TICK_INTERVAL_MS: "0", DATABASE_PATH: database, OWNER_TOKEN: "browser-live", WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") }; children.push(spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env, stdio: "ignore" })); children.push(spawn(process.execPath, [join(root, "node_modules", "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(webPort)], { cwd: join(root, "packages", "web"), env: { ...env, VITE_API_URL: `http://127.0.0.1:${apiPort}` }, stdio: "ignore" })); await waitFor(`http://127.0.0.1:${apiPort}/health`); await waitFor(`http://127.0.0.1:${webPort}/`); const reset = await fetch(`http://127.0.0.1:${apiPort}/api/owner/reset-v3`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": "browser-live" }, body: JSON.stringify({ bundleHash: hash, seed: 23 }) }); assert.equal(reset.status, 200);
  const browser = await chromium.launch({ headless: true }); try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } }); await page.goto(`http://127.0.0.1:${webPort}/`); await page.locator("#village-canvas canvas").waitFor(); const panel = page.getByTestId("first-glow-inspector"); await panel.waitFor(); const canvasBox = await page.locator("#village-canvas").boundingBox(); const panelBox = await panel.boundingBox(); const headerBox = await page.locator("header.first-glow-header").boundingBox(); const controls = page.locator("header.first-glow-header .controls"); const controlsBox = await controls.boundingBox(); assert.ok(canvasBox && panelBox && panelBox.x >= canvasBox.x + canvasBox.width, "selected-item panel must sit beside the map"); assert.ok(canvasBox && panelBox && panelBox.y <= canvasBox.y + 1 && panelBox.y + panelBox.height >= canvasBox.y + canvasBox.height - 1, "selected-item panel must span the map height"); assert.ok(canvasBox && controlsBox && controlsBox.x >= canvasBox.x + canvasBox.width, "live controls must sit in the right column"); assert.ok(headerBox && controlsBox && Math.abs(controlsBox.x - panelBox!.x) <= 1 && Math.abs(controlsBox.width - panelBox!.width) <= 1, `live controls must match selected-item width: controls=${JSON.stringify(controlsBox)} panel=${JSON.stringify(panelBox)}`); assert.ok(headerBox && controlsBox && Math.abs(controlsBox.y - headerBox.y) <= 1 && Math.abs(controlsBox.height - headerBox.height) <= 1, `live controls must match header height: controls=${JSON.stringify(controlsBox)} header=${JSON.stringify(headerBox)}`); assert.ok(canvasBox && controlsBox && controlsBox.y + controlsBox.height <= canvasBox.y + 1, `live controls must stay above the map: controls=${JSON.stringify(controlsBox)} map=${JSON.stringify(canvasBox)}`); assert.equal(await page.locator(".first-glow > .timeline").isVisible(), false); assert.equal(await page.getByText("Playback", { exact: true }).isVisible().catch(() => false), false); assert.equal(await controls.getByRole("button", { name: "Advance one tick" }).count(), 1); assert.equal(await page.getByTitle("Zoom in").count(), 1); assert.equal(await page.getByTitle("Zoom out").count(), 1); assert.equal(await page.getByTestId("objective-events").getByRole("status").innerText(), "No committed events have been recorded."); assert.equal(await page.getByTestId("social-interpretations").getByRole("status").innerText(), "No subjective interpretation has been recorded."); await page.getByRole("button", { name: "Advance one tick" }).focus(); assert.equal(await page.evaluate(() => (document.activeElement as HTMLElement | null)?.getAttribute("aria-label")), "Advance one tick"); const select = page.getByTestId("first-glow-entity-chooser").getByRole("combobox", { name: "Selected entity" }); await select.selectOption({ index: 1 }); assert.ok((await panel.innerText()).includes("Current location"));
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } }); await mobile.goto(`http://127.0.0.1:${webPort}/`); await mobile.getByTestId("first-glow-inspector").waitFor(); assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false); assert.equal(await mobile.locator(".first-glow > .timeline").isVisible(), false); const mobileMap = await mobile.locator("#village-canvas").boundingBox(); const mobileInspector = await mobile.getByTestId("first-glow-inspector").boundingBox(); assert.ok(mobileMap && mobileInspector && mobileInspector.y >= mobileMap.y + mobileMap.height - 1, "mobile inspector must follow the map"); console.log("First Glow live panel desktop, tablet, and mobile test passed");
  } finally { await browser.close(); }
} finally { await Promise.all(children.map(child => new Promise<void>(resolve => { if (child.exitCode !== null) { resolve(); return; } child.once("exit", () => resolve()); child.kill(); setTimeout(resolve, 3000); }))); for (const path of [database, `${database}-wal`, `${database}-shm`]) if (existsSync(path)) rmSync(path, { force: true }); }
