import { testPort, stopTestProcesses } from "../../../scripts/test-runtime.mjs";
import assert from "node:assert/strict";
import { chromium } from "playwright";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", ".."); const nodeModules = existsSync(join(root, "node_modules")) ? join(root, "node_modules") : join(root, "..", "..\\node_modules"); const apiPort = await testPort(); const webPort = await testPort(); const hash = "sha256-8e3425f460b2a53518e114b01a77a4937712cbd5028ab93427da34f6c3755601"; const database = join(root, ".tmp", "browser-tests", `first-glow-identity-${Date.now()}.db`); mkdirSync(join(root, ".tmp", "browser-tests"), { recursive: true }); const children: ChildProcess[] = [];
const waitFor = async (url: string) => { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(url)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`service did not start: ${url}`); };
try {
  const env = { ...process.env, PORT: String(apiPort), AUTO_PULSE: "false", PULSE_INTERVAL_MS: "0", DATABASE_PATH: database, OWNER_TOKEN: "browser-first-glow-identity", WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") };
  children.push(spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env, stdio: "ignore" })); children.push(spawn(process.execPath, [join(nodeModules, "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(webPort), "--strictPort"], { cwd: join(root, "packages", "web"), env: { ...env, VITE_API_URL: `http://127.0.0.1:${apiPort}` }, stdio: "ignore" })); await waitFor(`http://127.0.0.1:${apiPort}/health`); await waitFor(`http://127.0.0.1:${webPort}/`); const reset = await fetch(`http://127.0.0.1:${apiPort}/api/owner/reset-v3`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": env.OWNER_TOKEN }, body: JSON.stringify({ bundleHash: hash, seed: 23, sparkCount: 6 }) }); assert.equal(reset.status, 200);
  const browser = await chromium.launch({ headless: true }); try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } }); await page.goto(`http://127.0.0.1:${webPort}/`); await page.locator("#village-canvas canvas").waitFor(); await page.getByTestId("first-glow-inspector").waitFor(); await page.waitForTimeout(300);
    const signatures = JSON.parse(await page.locator("#village-canvas").getAttribute("data-rendered-spark-signatures") ?? "{}"); assert.equal(Object.keys(signatures).length, 6); assert.ok(new Set(Object.values(signatures)).size >= 4, "six Sparks should remain distinguishable in the browser"); assert.equal(await page.getByTestId("first-glow-spark-avatar").count(), 1);
    await page.getByTestId("first-glow-entity-chooser").getByRole("combobox").selectOption({ index: 2 }); const avatarLabel = await page.getByTestId("first-glow-spark-avatar").getAttribute("aria-label"); assert.match(avatarLabel ?? "", /Spark 2.*signature/); assert.equal(await page.getByTestId("first-glow-spark-avatar").getAttribute("data-spark-state"), "idle");
    await page.emulateMedia({ reducedMotion: "reduce" }); await page.reload(); await page.locator("#village-canvas canvas").waitFor(); await page.waitForTimeout(300); assert.equal(await page.evaluate(() => window.matchMedia("(prefers-reduced-motion: reduce)").matches), true); assert.equal(await page.locator("#village-canvas").getAttribute("data-reduced-motion"), "true"); assert.equal(await page.getByTestId("first-glow-spark-avatar").count(), 1); console.log("First Glow Spark identity browser checks passed");
  } finally { await browser.close(); }
} finally { await stopTestProcesses(children); for (const path of [database, `${database}-wal`, `${database}-shm`]) if (existsSync(path)) rmSync(path, { force: true }); }
