import assert from "node:assert/strict";
import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", "..");
const apiPort = 34211;
const webPort = 5188;
const hash = "sha256-92cc5cee6d8859375c046057ef6341fa6844cf6cbe610177d1d81726af0decf3";
const children: ChildProcess[] = [];
const waitFor = async (url: string) => { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(url)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`service did not start: ${url}`); };
try {
  const database = join(root, `first-glow-browser-${Date.now()}.db`);
  const env = { ...process.env, PORT: String(apiPort), AUTO_TICK: "false", TICK_INTERVAL_MS: "0", DATABASE_PATH: database, OWNER_TOKEN: "browser-first-glow", WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") };
  children.push(spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env, stdio: "ignore" }));
  children.push(spawn(process.execPath, [join(root, "node_modules", "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(webPort)], { cwd: join(root, "packages", "web"), env: { ...env, VITE_API_URL: `http://127.0.0.1:${apiPort}` }, stdio: "ignore" }));
  await waitFor(`http://127.0.0.1:${apiPort}/health`); await waitFor(`http://127.0.0.1:${webPort}/`);
  const reset = await fetch(`http://127.0.0.1:${apiPort}/api/owner/reset-v3`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": "browser-first-glow" }, body: JSON.stringify({ bundleHash: hash, seed: 23 }) }); assert.equal(reset.status, 200);
  const browser = await chromium.launch({ headless: true });
  try {
    const desktop = await browser.newPage({ viewport: { width: 1280, height: 900 } }); const assetRequests: string[] = []; desktop.on("request", request => { if (request.url().includes(`/api/world/bundles/${hash}/assets/`)) assetRequests.push(request.url()); }); await desktop.goto(`http://127.0.0.1:${webPort}/`); await desktop.locator('main[data-theme="living-circuit"]').waitFor(); await desktop.locator("#village-canvas canvas").first().waitFor(); await desktop.getByTestId("first-glow-inspector").waitFor(); await desktop.waitForTimeout(300); assert.ok(assetRequests.length >= 5, `expected manifest assets to load, got ${assetRequests.length}`);
    const style = await desktop.locator("main").evaluate(element => ({ background: getComputedStyle(element).backgroundColor, width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth })); assert.equal(style.background, "rgb(5, 9, 18)"); assert.ok(style.width <= style.viewport + 1);
    assert.equal(await desktop.locator("main.first-glow aside").evaluate(element => getComputedStyle(element).display), "none"); assert.ok(await desktop.getByTestId("first-glow-inspector").getByText("Charge deficit").count() > 0); assert.ok(await desktop.getByTestId("first-glow-inspector").getByText("stable signature").count() > 0);
    await desktop.getByRole("button", { name: "Show IDs" }).click(); assert.ok(await desktop.getByTestId("first-glow-inspector").getByText("spark-1").count() > 0); const overlaySummary = await desktop.getByTestId("first-glow-overlay-summary").textContent(); assert.match(overlaySummary ?? "", /nav:0/); assert.match(overlaySummary ?? "", /surfaces:/); assert.match(overlaySummary ?? "", /contacts:/); assert.match(overlaySummary ?? "", /reservations:none/); await desktop.getByRole("button", { name: "+", exact: true }).click(); await desktop.getByRole("button", { name: "Fit", exact: true }).click(); await desktop.setViewportSize({ width: 1024, height: 768 }); await desktop.locator("#village-canvas canvas").first().waitFor(); assert.equal(await desktop.getByTestId("first-glow-overlay-summary").count(), 1); await desktop.screenshot({ path: join(root, "docs", "evidence", "first-glow-desktop-overlay.png"), fullPage: true }); await desktop.getByRole("button", { name: "Hide IDs" }).click(); assert.equal(await desktop.getByTestId("first-glow-inspector").getByText("spark-1").count(), 0); assert.equal(await desktop.getByTestId("first-glow-overlay-summary").count(), 0);
    mkdirSync(join(root, "docs", "evidence"), { recursive: true }); await desktop.screenshot({ path: join(root, "docs", "evidence", "first-glow-desktop.png"), fullPage: true });
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } }); await mobile.goto(`http://127.0.0.1:${webPort}/`); await mobile.locator('main[data-theme="living-circuit"]').waitFor(); const mobileOverflow = await mobile.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth, wide: [...document.querySelectorAll("*")].map(element => ({ tag: element.tagName, width: (element as HTMLElement).getBoundingClientRect().width })).filter(item => item.width > document.documentElement.clientWidth + 1).slice(0, 5) })); if (mobileOverflow.width > mobileOverflow.viewport + 1) throw new Error(`mobile overflow: ${JSON.stringify(mobileOverflow)}`); await mobile.screenshot({ path: join(root, "docs", "evidence", "first-glow-mobile.png"), fullPage: true }); await mobile.getByRole("button", { name: "Show IDs" }).click(); assert.ok(await mobile.getByTestId("first-glow-overlay-summary").count() > 0); await mobile.screenshot({ path: join(root, "docs", "evidence", "first-glow-mobile-overlay.png"), fullPage: true }); await mobile.getByRole("button", { name: "Hide IDs" }).click();
    await desktop.getByRole("button", { name: "0.5×" }).click(); await mobile.getByRole("button", { name: "2×" }).click();
    for (let step = 0; step < 2; step += 1) { const response = await fetch(`http://127.0.0.1:${apiPort}/api/tick`, { method: "POST", headers: { "x-owner-token": "browser-first-glow" } }); assert.equal(response.status, 200); }
    await desktop.getByText("Tick 2 / 2").waitFor(); await mobile.getByText("Tick 2 / 2").waitFor(); const desktopInspector = await desktop.getByTestId("first-glow-inspector").textContent(); const mobileInspector = await mobile.getByTestId("first-glow-inspector").textContent(); assert.equal(desktopInspector, mobileInspector); const authoritative = await (await fetch(`http://127.0.0.1:${apiPort}/api/world`)).json() as { state: { firstGlowState?: { settlements: { sparks: { id: string; position: { x: number; y: number } }[] }[] } } }; const expectedCoordinates = Object.fromEntries((authoritative.state.firstGlowState?.settlements[0].sparks ?? []).map(spark => [spark.id, { x: spark.position.x * 24 + 12, y: spark.position.y * 24 + 12 }])); for (const page of [desktop, mobile]) { const rendered = JSON.parse(await page.locator("#village-canvas").getAttribute("data-rendered-spark-coordinates") ?? "{}"); assert.deepEqual(rendered, expectedCoordinates); }
    console.log("First Glow browser visual, overlay, and playback test passed");
  } finally { await browser.close(); }
} finally { await Promise.all(children.map(child => new Promise<void>(resolve => { if (child.exitCode !== null) { resolve(); return; } child.once("exit", () => resolve()); child.kill(); setTimeout(resolve, 3000); }))); }
