import assert from "node:assert/strict";
import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", ".."); const apiPort = 34211; const webPort = 5188; const hash = "sha256-92cc5cee6d8859375c046057ef6341fa6844cf6cbe610177d1d81726af0decf3"; const children: ChildProcess[] = [];
const waitFor = async (url: string) => { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(url)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`service did not start: ${url}`); };
try {
  const database = join(root, `first-glow-browser-${Date.now()}.db`); const env = { ...process.env, PORT: String(apiPort), AUTO_TICK: "false", TICK_INTERVAL_MS: "0", DATABASE_PATH: database, OWNER_TOKEN: "browser-first-glow", WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") };
  children.push(spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env, stdio: "ignore" })); children.push(spawn(process.execPath, [join(root, "node_modules", "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(webPort)], { cwd: join(root, "packages", "web"), env: { ...env, VITE_API_URL: `http://127.0.0.1:${apiPort}` }, stdio: "ignore" })); await waitFor(`http://127.0.0.1:${apiPort}/health`); await waitFor(`http://127.0.0.1:${webPort}/`);
  const reset = await fetch(`http://127.0.0.1:${apiPort}/api/owner/reset-v3`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": "browser-first-glow" }, body: JSON.stringify({ bundleHash: hash, seed: 23 }) }); assert.equal(reset.status, 200); const browser = await chromium.launch({ headless: true }); try { const desktop = await browser.newPage({ viewport: { width: 1280, height: 900 } }); await desktop.goto(`http://127.0.0.1:${webPort}/`); await desktop.locator('main[data-theme="living-circuit"]').waitFor(); const canvas = desktop.locator("#village-canvas canvas").first(); await canvas.waitFor(); const style = await desktop.locator("main").evaluate(element => ({ background: getComputedStyle(element).backgroundColor, width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth })); assert.equal(style.background, "rgb(5, 9, 18)"); assert.ok(style.width <= style.viewport + 1); mkdirSync(join(root, "docs", "evidence"), { recursive: true }); await desktop.screenshot({ path: join(root, "docs", "evidence", "first-glow-desktop.png"), fullPage: true }); const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } }); await mobile.goto(`http://127.0.0.1:${webPort}/`); await mobile.locator('main[data-theme="living-circuit"]').waitFor(); const mobileOverflow = await mobile.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth })); assert.ok(mobileOverflow.width <= mobileOverflow.viewport + 1); await mobile.screenshot({ path: join(root, "docs", "evidence", "first-glow-mobile.png"), fullPage: true }); console.log("First Glow browser visual test passed"); } finally { await browser.close(); }
} finally { await Promise.all(children.map(child => new Promise<void>(resolve => { if (child.exitCode !== null) { resolve(); return; } child.once("exit", () => resolve()); child.kill(); setTimeout(resolve, 3000); }))); }
