import assert from "node:assert/strict";
import { chromium } from "playwright";
import { mkdirSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", "..");
const nodeModules = existsSync(join(root, "node_modules")) ? join(root, "node_modules") : join(root, "..", "..", "node_modules");
const apiPort = 34211;
const webPort = 5188;
const hash = "sha256-8e3425f460b2a53518e114b01a77a4937712cbd5028ab93427da34f6c3755601";
const tempRoot = join(root, ".tmp", "browser-tests");
mkdirSync(tempRoot, { recursive: true });
const database = join(tempRoot, `first-glow-browser-${Date.now()}.db`);
const children: ChildProcess[] = [];
const waitFor = async (url: string) => { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(url)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`service did not start: ${url}`); };
try {
  const env = { ...process.env, PORT: String(apiPort), AUTO_PULSE: "false", PULSE_INTERVAL_MS: "0", DATABASE_PATH: database, OWNER_TOKEN: "browser-first-glow", OBSERVER_ORIGIN: `http://127.0.0.1:${webPort}`, WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") };
  children.push(spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env, stdio: "ignore" }));
  children.push(spawn(process.execPath, [join(nodeModules, "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(webPort)], { cwd: join(root, "packages", "web"), env: { ...env, VITE_API_URL: `http://127.0.0.1:${apiPort}` }, stdio: "ignore" }));
  await waitFor(`http://127.0.0.1:${apiPort}/health`); await waitFor(`http://127.0.0.1:${webPort}/`);
    const reset = await fetch(`http://127.0.0.1:${apiPort}/api/owner/reset-v3`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": "browser-first-glow" }, body: JSON.stringify({ bundleHash: hash, seed: 23, sparkCount: 6 }) }); assert.equal(reset.status, 200);
  const browser = await chromium.launch({ headless: true });
  try {
    const desktop = await browser.newPage({ viewport: { width: 1280, height: 900 } }); const assetRequests: string[] = []; const assetStatuses: number[] = []; desktop.on("request", request => { if (request.url().includes(`/api/world/bundles/${hash}/assets/`)) assetRequests.push(request.url()); }); desktop.on("response", response => { if (response.url().includes(`/api/world/bundles/${hash}/assets/`)) assetStatuses.push(response.status()); }); await desktop.goto(`http://127.0.0.1:${webPort}/`); await desktop.locator('main[data-theme="living-circuit"]').waitFor(); await desktop.locator("#village-canvas canvas").first().waitFor(); await desktop.getByTestId("first-glow-inspector").waitFor(); const designPanel = desktop.getByTestId("first-glow-design"); await designPanel.waitFor(); assert.equal(await designPanel.getByTestId("first-glow-card").count(), 6); assert.equal(await designPanel.getByTestId("first-glow-dilemma").count(), 4); assert.equal(await designPanel.getByText("A pool grows quiet").count(), 1); assert.equal(await designPanel.getByText("Objective observations").count(), 4); assert.equal(await designPanel.getByText("Possible durable consequences:").count(), 8); assert.ok((await designPanel.innerText()).includes("valueTendencies") === false); const firstGlowCopy = (await desktop.locator("main").innerText()).toLowerCase(); assert.match(firstGlowCopy, /what keeps our lights on\?/); assert.match(firstGlowCopy, /originators/); assert.equal(firstGlowCopy.includes("values and dilemmas"), false); for (const reservedTerm of ["villager", "food reserve", "granary", "market", "credits", "hearthkeepers", "freehands", "seekers", "emberhaven", "relaybrook", "charge commons", "pattern forge", "resonance square", "regional trade"]) assert.equal(firstGlowCopy.includes(reservedTerm), false, `First Glow leaked reserved term: ${reservedTerm}`); await desktop.waitForTimeout(500); assert.ok(assetRequests.length >= 4, `expected manifest assets to load, got ${assetRequests.length}`); assert.ok(assetStatuses.length >= 4, `expected manifest assets to receive responses, got ${assetStatuses.length}`); assert.ok(assetStatuses.every(status => status === 200), `manifest assets returned non-200 statuses: ${assetStatuses.join(", ")}`); assert.equal(await desktop.getByAltText("Mimir light mark").getAttribute("src"), "/mimir-light-mark.svg");
    const style = await desktop.locator("main").evaluate(element => ({ background: getComputedStyle(element).backgroundColor, width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth })); assert.equal(style.background, "rgb(5, 9, 18)"); assert.ok(style.width <= style.viewport + 1); const desktopCanvas = await desktop.locator("#village-canvas canvas").evaluate(canvas => ({ backingWidth: canvas.width, backingHeight: canvas.height, displayWidth: canvas.getBoundingClientRect().width, displayHeight: canvas.getBoundingClientRect().height, resolution: canvas.dataset.renderResolution, cameraZoom: canvas.dataset.cameraZoom, cameraViewCells: canvas.dataset.cameraViewCells })); assert.equal(desktopCanvas.resolution, "1"); assert.equal(desktopCanvas.backingWidth, 768); assert.equal(desktopCanvas.backingHeight, 768); assert.ok(Math.abs(desktopCanvas.displayWidth - desktopCanvas.displayHeight) < 1); assert.equal(desktopCanvas.cameraZoom, "1"); assert.equal(desktopCanvas.cameraViewCells, "32");
    assert.equal(await desktop.locator("main.first-glow aside").evaluate(element => getComputedStyle(element).display), "none"); await desktop.getByTestId("first-glow-entity-chooser").getByRole("combobox").selectOption({ index: 1 }); const inspectorCopy = (await desktop.getByTestId("first-glow-inspector").innerText()).toLowerCase(); for (const field of ["current location", "contact", "destination", "activity", "status / wait reason", "travel progress", "charge", "charge deficit", "readiness"]) assert.ok(inspectorCopy.includes(field), `Spark inspector omitted ${field}`); assert.ok(inspectorCopy.includes("stable signature")); assert.equal(inspectorCopy.includes("spark-"), false, "raw Spark IDs must stay hidden outside developer mode");
    assert.equal(await desktop.getByRole("button", { name: "Show IDs" }).count(), 0); const desktopCanvasBox = await desktop.locator("#village-canvas canvas").boundingBox(); assert.ok(desktopCanvasBox); await desktop.locator("#village-canvas canvas").hover({ position: { x: desktopCanvasBox!.width / 2, y: desktopCanvasBox!.height / 2 } }); const desktopCellTooltip = desktop.getByTestId("first-glow-cell-tooltip"); await desktopCellTooltip.waitFor(); assert.match((await desktopCellTooltip.textContent()) ?? "", /Cell \(\d+, \d+\)/); await desktop.screenshot({ path: join(root, "docs", "evidence", "first-glow-desktop-overlay.png"), fullPage: true }); const livePanel = desktop.locator("header.first-glow-header"); await livePanel.getByRole("button", { name: "Zoom in" }).click(); await livePanel.getByRole("button", { name: "Fit map" }).click(); await desktop.locator("#village-canvas canvas").dispatchEvent("wheel", { deltaY: -100 }); await desktop.locator("#village-canvas canvas").dispatchEvent("wheel", { deltaY: 100 }); await livePanel.getByRole("button", { name: "Fit map" }).click(); await livePanel.getByRole("button", { name: "Zoom in" }).click();
    const dragCanvas = async (toward: "top-left" | "bottom-right") => {
      const box = await desktop.locator("#village-canvas canvas").boundingBox(); assert.ok(box);
      const start = { x: box!.x + box!.width / 2, y: box!.y + box!.height / 2 };
      const end = toward === "top-left" ? { x: box!.x + 4, y: box!.y + 4 } : { x: box!.x + box!.width - 4, y: box!.y + box!.height - 4 };
      await desktop.mouse.move(start.x, start.y); await desktop.mouse.down(); await desktop.mouse.move(end.x, end.y, { steps: 8 }); await desktop.mouse.up();
    };
    for (let attempt = 0; attempt < 5; attempt += 1) await dragCanvas("top-left");
    const movedScroll = (await desktop.locator("#village-canvas canvas").getAttribute("data-camera-scroll") ?? "0,0").split(",").map(Number);
    assert.ok(movedScroll[0] > 0 && movedScroll[1] > 0, `dragging up-left must move across the map, got ${movedScroll.join(",")}`);
    for (let attempt = 0; attempt < 5; attempt += 1) await dragCanvas("bottom-right");
    assert.equal(await desktop.locator("#village-canvas canvas").getAttribute("data-camera-scroll"), "0,0", "dragging down-right reaches the top-left map boundary");
    await desktop.setViewportSize({ width: 1024, height: 768 }); await desktop.locator("#village-canvas canvas").first().waitFor();
    mkdirSync(join(root, "docs", "evidence"), { recursive: true }); await desktop.screenshot({ path: join(root, "docs", "evidence", "first-glow-desktop.png"), fullPage: true });
    const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 }); const mobile = await mobileContext.newPage(); await mobile.goto(`http://127.0.0.1:${webPort}/`); await mobile.locator('main[data-theme="living-circuit"]').waitFor(); const mobileOverflow = await mobile.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth, wide: [...document.querySelectorAll("*")].map(element => ({ tag: element.tagName, width: (element as HTMLElement).getBoundingClientRect().width })).filter(item => item.width > document.documentElement.clientWidth + 1).slice(0, 5) })); if (mobileOverflow.width > mobileOverflow.viewport + 1) throw new Error(`mobile overflow: ${JSON.stringify(mobileOverflow)}`); const mobileCanvas = await mobile.locator("#village-canvas canvas").evaluate(canvas => ({ backingWidth: canvas.width, backingHeight: canvas.height, displayWidth: canvas.getBoundingClientRect().width, displayHeight: canvas.getBoundingClientRect().height, resolution: canvas.dataset.renderResolution, cameraZoom: canvas.dataset.cameraZoom, cameraViewCells: canvas.dataset.cameraViewCells })); assert.equal(mobileCanvas.resolution, "2"); assert.equal(mobileCanvas.backingWidth, 1536); assert.equal(mobileCanvas.backingHeight, 1536); assert.ok(Math.abs(mobileCanvas.displayWidth - mobileCanvas.displayHeight) < 1); assert.equal(mobileCanvas.cameraZoom, "1"); assert.equal(mobileCanvas.cameraViewCells, "32"); await mobile.screenshot({ path: join(root, "docs", "evidence", "first-glow-mobile.png"), fullPage: true }); assert.equal(await mobile.getByRole("button", { name: "Show IDs" }).count(), 0); const mobileCanvasBox = await mobile.locator("#village-canvas canvas").boundingBox(); assert.ok(mobileCanvasBox); await mobile.locator("#village-canvas canvas").hover({ position: { x: mobileCanvasBox!.width / 2, y: mobileCanvasBox!.height / 2 } }); const mobileCellTooltip = mobile.getByTestId("first-glow-cell-tooltip"); await mobileCellTooltip.waitFor(); assert.match((await mobileCellTooltip.textContent()) ?? "", /Cell \(\d+, \d+\)/); await mobile.screenshot({ path: join(root, "docs", "evidence", "first-glow-mobile-overlay.png"), fullPage: true });
    assert.equal(await desktop.getByText("Playback", { exact: true }).isVisible().catch(() => false), false); assert.equal(await mobile.getByText("Playback", { exact: true }).isVisible().catch(() => false), false);
    for (const page of [desktop, mobile]) await page.evaluate(() => { (window as typeof window & { __mimirCanvas?: HTMLCanvasElement }).__mimirCanvas = document.querySelector("#village-canvas canvas") ?? undefined; });
    for (let step = 0; step < 2; step += 1) { const response = await fetch(`http://127.0.0.1:${apiPort}/api/pulse`, { method: "POST", headers: { "x-owner-token": "browser-first-glow" } }); assert.equal(response.status, 200); }
    for (const page of [desktop, mobile]) assert.equal(await page.evaluate(() => (window as typeof window & { __mimirCanvas?: HTMLCanvasElement }).__mimirCanvas === document.querySelector("#village-canvas canvas")), true, "First Glow canvas was recreated between committed pulses"); const authoritative = await (await fetch(`http://127.0.0.1:${apiPort}/api/world`)).json() as { state: { firstGlowState?: { settlements: { sparks: { id: string; position: { x: number; y: number } }[] }[]; explanations?: { pulse: number }[] } } }; const expectedCoordinates = Object.fromEntries((authoritative.state.firstGlowState?.settlements[0].sparks ?? []).map(spark => [spark.id, { x: spark.position.x * 24 + 12, y: spark.position.y * 24 + 12 }])); const coordinatesMatch = (actual: Record<string, { x: number; y: number }>, expected: Record<string, { x: number; y: number }>) => JSON.stringify(Object.entries(actual).sort(([left], [right]) => left.localeCompare(right))) === JSON.stringify(Object.entries(expected).sort(([left], [right]) => left.localeCompare(right))); for (const page of [desktop, mobile]) { await page.waitForFunction(expected => { const rendered = document.querySelector("#village-canvas")?.getAttribute("data-rendered-spark-coordinates"); return rendered ? (Object.entries(JSON.parse(rendered) as Record<string, { x: number; y: number }>).sort(([left], [right]) => left.localeCompare(right)).join("|") === Object.entries(expected as Record<string, { x: number; y: number }>).sort(([left], [right]) => left.localeCompare(right)).join("|")) : false; }, expectedCoordinates); } for (const page of [desktop, mobile]) { const inspectorCopy = await page.getByTestId("first-glow-inspector").innerText(); assert.equal(inspectorCopy.includes("Selected item"), false); assert.equal(inspectorCopy.includes("Current Spark or light-site details."), false); assert.equal(/\d+ Sparks · \d+ sites/.test(inspectorCopy), false); assert.equal(inspectorCopy.includes("spark-"), false, "raw Spark IDs must stay hidden outside developer mode"); const rendered = JSON.parse(await page.locator("#village-canvas").getAttribute("data-rendered-spark-coordinates") ?? "{}"); assert.equal(coordinatesMatch(rendered, expectedCoordinates), true); }
    let explanationState = authoritative.state.firstGlowState;
    for (let attempt = 0; attempt < 12 && !(explanationState?.explanations?.length); attempt += 1) {
      const response = await fetch(`http://127.0.0.1:${apiPort}/api/pulse`, { method: "POST", headers: { "x-owner-token": "browser-first-glow" } }); assert.equal(response.status, 200);
      const latest = await (await fetch(`http://127.0.0.1:${apiPort}/api/world`)).json() as { state: { firstGlowState?: { explanations?: { pulse: number }[] } } };
      explanationState = latest.state.firstGlowState;
    }
    for (let attempt = 0; attempt < 100; attempt += 1) { const response = await fetch(`http://127.0.0.1:${apiPort}/api/pulse`, { method: "POST", headers: { "x-owner-token": "browser-first-glow" } }); if (response.status === 409) break; assert.equal(response.status, 200); }
    explanationState = (await (await fetch(`http://127.0.0.1:${apiPort}/api/world`)).json()).state.firstGlowState;
    assert.deepEqual([...new Set(explanationState?.explanations?.map(explanation => explanation.dilemmaId) ?? [])].sort(), ["public-or-private-mark", "shelter-or-trace", "weakening-pool-report"]);
    assert.ok(explanationState?.explanations?.length, "committed First Glow pulses should expose at least one explanation chain");
    await desktop.reload(); await desktop.locator('main[data-theme="living-circuit"]').waitFor(); await desktop.getByTestId("first-glow-explanations").getByTestId("first-glow-explanation").first().waitFor();
    const historicalPulse = explanationState!.explanations![0].pulse;
    await desktop.locator("#timeline").evaluate((element, value) => { const input = element as HTMLInputElement; input.value = String(value); input.dispatchEvent(new Event("input", { bubbles: true })); input.dispatchEvent(new Event("change", { bubbles: true })); }, historicalPulse);
    await desktop.waitForTimeout(250);
    assert.ok(await desktop.getByTestId("first-glow-explanation").count() > 0, "historical First Glow view should retain the explanation chain");
    for (const page of [desktop, mobile]) { const copy = await page.getByTestId("social-interpretations").innerText(); assert.equal(copy.includes("NaN%"), false); assert.ok(copy.includes("status rules baseline") || copy.includes("status deterministic fallback")); }
    console.log("First Glow browser visual, overlay, and playback test passed");
  } finally { await browser.close(); }
} finally {
  await Promise.all(children.map(child => new Promise<void>(resolve => { if (child.exitCode !== null) { resolve(); return; } child.once("exit", () => resolve()); child.kill(); setTimeout(resolve, 3000); })));
  for (const path of [database, `${database}-wal`, `${database}-shm`]) if (existsSync(path)) rmSync(path, { force: true });
}
