import assert from "node:assert/strict";
import { chromium } from "playwright";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", ".."); const apiPort = 34239; const webPort = 5209; const hash = "sha256-8e3425f460b2a53518e114b01a77a4937712cbd5028ab93427da34f6c3755601"; const database = join(root, ".tmp", "browser-tests", `history-viewer-${Date.now()}.db`); mkdirSync(join(root, ".tmp", "browser-tests"), { recursive: true }); const children: ChildProcess[] = [];
const waitFor = async (url: string) => { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(url)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`service did not start: ${url}`); };
try {
  const env = { ...process.env, PORT: String(apiPort), AUTO_TICK: "false", TICK_INTERVAL_MS: "0", DATABASE_PATH: database, OWNER_TOKEN: "history-viewer", WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") };
  children.push(spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env, stdio: "ignore" })); children.push(spawn(process.execPath, [join(root, "node_modules", "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(webPort)], { cwd: join(root, "packages", "web"), env: { ...env, VITE_API_URL: `http://127.0.0.1:${apiPort}` }, stdio: "ignore" })); await waitFor(`http://127.0.0.1:${apiPort}/health`); await waitFor(`http://127.0.0.1:${webPort}/`);
  assert.equal((await fetch(`http://127.0.0.1:${apiPort}/api/owner/reset-v3`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": env.OWNER_TOKEN }, body: JSON.stringify({ bundleHash: hash, seed: 39 }) })).status, 200); assert.equal((await fetch(`http://127.0.0.1:${apiPort}/api/tick`, { method: "POST", headers: { "x-owner-token": env.OWNER_TOKEN } })).status, 200);
  const browser = await chromium.launch({ headless: true }); try { const page = await browser.newPage({ viewport: { width: 1000, height: 800 } }); await page.goto(`http://127.0.0.1:${webPort}/?view=history`); await page.getByTestId("history-viewer").waitFor(); assert.ok((await page.getByText("Selected historical state").count()) === 1); assert.ok((await page.getByText("recorded outcomes and readings only").count()) === 1); assert.ok((await page.getByText("Simulation").count()) === 1); assert.ok((await page.getByText(/Tick 1/).count()) >= 1); assert.ok((await page.getByText("Return to live observer").count()) === 1); const live = await page.goto(`http://127.0.0.1:${webPort}/`); assert.ok(live); await page.locator(".history-entry-float").waitFor(); console.log("Dedicated First Glow history viewer browser test passed"); } finally { await browser.close(); }
} finally { await Promise.all(children.map(child => new Promise<void>(resolve => { if (child.exitCode !== null) { resolve(); return; } child.once("exit", () => resolve()); child.kill(); setTimeout(resolve, 3000); }))); for (const path of [database, `${database}-wal`, `${database}-shm`]) if (existsSync(path)) rmSync(path, { force: true }); }
