import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", ".."); const stamp = Date.now(); const database = join(root, `backup-v2-${stamp}.db`); const backup = join(root, `backup-v2-${stamp}-copy.db`); const restored = join(root, `backup-v2-${stamp}-restored.db`); const corrupt = join(root, `backup-v2-${stamp}-corrupt.db`); const port = 34135; const hash = "sha256-b8e2c3b01dfbf1f1710a28a4f8877640acbe56b42fd103612ae5d6ae54e9adae"; let server: ChildProcess | undefined;
async function waitFor() { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(`http://127.0.0.1:${port}/health`)).ok) return; } catch { /* startup */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error("backup fixture server did not start"); }
async function stop() { if (server && server.exitCode === null) { server.kill(); await new Promise<void>(resolve => { server?.once("exit", () => resolve()); setTimeout(resolve, 3000); }); } }
try {
  server = spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env: { ...process.env, PORT: String(port), AUTO_TICK: "false", DATABASE_PATH: database, OWNER_TOKEN: "backup-owner" }, stdio: "ignore" }); await waitFor(); const reset = await fetch(`http://127.0.0.1:${port}/api/owner/reset-v2`, { method: "POST", headers: { "content-type": "application/json", "x-owner-token": "backup-owner" }, body: JSON.stringify({ bundleHash: hash, seed: 19 }) }); assert.equal(reset.status, 200, await reset.text()); await stop(); server = undefined;
  const env = { ...process.env, DATABASE_PATH: database, WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") }; execFileSync(process.execPath, ["dist/backup.js", "backup", backup], { cwd: join(root, "packages", "server"), env, stdio: "pipe" }); const manifest = JSON.parse(readFileSync(`${backup}.manifest.json`, "utf8")) as { bundleHashes: string[]; bundleFiles: { hash: string }[] }; assert.deepEqual(manifest.bundleHashes, [hash]); assert.equal(manifest.bundleFiles[0].hash, hash); execFileSync(process.execPath, ["dist/backup.js", "restore", backup, restored], { cwd: join(root, "packages", "server"), env, stdio: "pipe" }); assert.ok(existsSync(`${restored}.bundles/${hash}/world.json`));
  execFileSync(process.execPath, ["dist/backup.js", "backup", corrupt], { cwd: join(root, "packages", "server"), env: { ...env, DATABASE_PATH: restored }, stdio: "pipe" }); writeFileSync(`${corrupt}.bundles/${hash}/world.json`, "corrupt\n"); assert.throws(() => execFileSync(process.execPath, ["dist/backup.js", "restore", corrupt, `${corrupt}-restored.db`], { cwd: join(root, "packages", "server"), env, stdio: "pipe" }), /checksum mismatch/); console.log("bundle-inclusive backup/restore passed");
} finally { await stop(); for (const path of [database, backup, restored, corrupt, `${database}-shm`, `${database}-wal`, `${backup}-shm`, `${backup}-wal`, `${restored}-shm`, `${restored}-wal`, `${corrupt}-shm`, `${corrupt}-wal`]) if (existsSync(path)) unlinkSync(path); for (const path of [`${backup}.manifest.json`, `${corrupt}.manifest.json`, `${backup}.bundles`, `${corrupt}.bundles`, `${restored}.bundles`, `${corrupt}-restored.db`]) if (existsSync(path)) rmSync(path, { recursive: true, force: true }); }
