import assert from "node:assert/strict";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";

const root = join(process.cwd(), "..", ".."); const tempRoot = join(root, ".tmp", `first-glow-commands-${Date.now()}`); const port = 34143; const database = join(tempRoot, "commands.db"); const hash = "sha256-8e3425f460b2a53518e114b01a77a4937712cbd5028ab93427da34f6c3755601"; let server: ChildProcess | undefined; const serverOutput: string[] = [];
const waitFor = async () => { for (let attempt = 0; attempt < 300; attempt += 1) { if (server?.exitCode !== null && server?.exitCode !== undefined) throw new Error(`First Glow command server exited with code ${server.exitCode}: ${serverOutput.join("")}`); try { if ((await fetch(`http://127.0.0.1:${port}/health`)).ok) return; } catch { /* starting */ } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`First Glow command server did not start within 30 seconds: ${serverOutput.join("")}`); };
const request = async (path: string, init?: RequestInit) => fetch(`http://127.0.0.1:${port}${path}`, { ...init, headers: { "x-owner-token": "first-glow-command-owner", ...(init?.headers ?? {}) } });
try {
  mkdirSync(tempRoot, { recursive: true });
  server = spawn(process.execPath, [join(root, "packages", "server", "dist", "index.js")], { cwd: root, env: { ...process.env, PORT: String(port), AUTO_TICK: "false", DATABASE_PATH: database, OWNER_TOKEN: "first-glow-command-owner", WORLD_BUNDLE_ROOT: join(root, "assets", "world", "generated") }, stdio: ["ignore", "pipe", "pipe"] }); server.stdout?.on("data", chunk => serverOutput.push(String(chunk))); server.stderr?.on("data", chunk => serverOutput.push(String(chunk))); await waitFor();
  const reset = await request("/api/owner/reset-v3", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ bundleHash: hash, seed: 41 }) }); assert.equal(reset.status, 200);
  const design = await (await request("/api/design")).json() as { themeId?: string; ageId?: string; firstGlow?: { openingQuestion?: string; boundary?: string; events?: { title: string }[]; cards?: { id: string }[]; dilemmas?: { id: string; alternatives: unknown[] }[] }; characterCards?: unknown[]; dilemmas?: unknown[] }; assert.equal(design.themeId, "living-circuit"); assert.equal(design.ageId, "first-glow"); assert.equal(design.firstGlow?.openingQuestion, "What keeps our lights on?"); assert.match(design.firstGlow?.boundary ?? "", /Originators/); assert.deepEqual(design.firstGlow?.events?.map(event => event.title), ["A pool grows quiet", "An unfamiliar trace"]); assert.equal(design.firstGlow?.cards?.length, 6); assert.deepEqual(design.firstGlow?.dilemmas?.map(dilemma => dilemma.id), ["weakening-pool-report", "shelter-or-trace", "public-or-private-mark"]); assert.ok(design.firstGlow?.dilemmas?.every(dilemma => dilemma.alternatives.length >= 2)); assert.deepEqual(design.characterCards, []); assert.deepEqual(design.dilemmas, []);
  const report = await (await request("/api/report")).json() as { summary?: { firstGlow?: { sourceCharge?: number; sparks?: number }; finalFood?: number; averageTrust?: number } }; assert.equal(report.summary?.firstGlow?.sourceCharge, 24); assert.equal(report.summary?.firstGlow?.sparks, 1); assert.equal(report.summary?.finalFood, 0); assert.equal(report.summary?.averageTrust, 0);
  const commandBody = { settlementId: "first-glow-region", objectId: "tiled-101", blocked: true, idempotencyKey: "close-opening-pool" };
  const queued = await request("/api/owner/world/object", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(commandBody) }); assert.equal(queued.status, 202, await queued.text()); const before = await (await request("/api/world")).json() as { state: { firstGlowState: { settlements: { runtime: { navigationRevision: number; objects: { objectId: string; blocked: boolean }[] } }[] } } }; assert.equal(before.state.firstGlowState.settlements[0].runtime.objects.length, 0);
  const repeated = await request("/api/owner/world/object", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(commandBody) }); assert.equal(repeated.status, 202);
  const tick = await request("/api/tick", { method: "POST" }); assert.equal(tick.status, 200); const after = await tick.json() as { state: { firstGlowState: { settlements: { runtime: { navigationRevision: number; objects: { objectId: string; blocked: boolean }[] } }[] } } }; const runtime = after.state.firstGlowState.settlements[0].runtime; assert.equal(runtime.navigationRevision, 1); assert.deepEqual(runtime.objects, [{ objectId: "tiled-101", blocked: true }]);
  const resetForBranch = await request("/api/owner/reset-v3", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ bundleHash: hash, seed: 47 }) }); assert.equal(resetForBranch.status, 200);
  const parentCommand = { settlementId: "first-glow-region", objectId: "tiled-101", blocked: true, idempotencyKey: "parent-only-command" }; const parentQueued = await request("/api/owner/world/object", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(parentCommand) }); assert.equal(parentQueued.status, 202);
  const branch = await request("/api/owner/branch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tick: 0 }) }); assert.equal(branch.status, 200); const branchState = await branch.json() as { state: { tick: number; firstGlowState: { settlements: { runtime: { objects: unknown[] } }[] } } }; assert.equal(branchState.state.tick, 0); assert.deepEqual(branchState.state.firstGlowState.settlements[0].runtime.objects, []);
  const branchTick = await request("/api/tick", { method: "POST" }); assert.equal(branchTick.status, 200); const branchAfter = await branchTick.json() as { state: { firstGlowState: { settlements: { runtime: { objects: unknown[] } }[] } } }; assert.deepEqual(branchAfter.state.firstGlowState.settlements[0].runtime.objects, []);
  console.log("First Glow queued command application and idempotency passed");
} finally { if (server && server.exitCode === null) { await new Promise<void>((resolve) => { server!.once("exit", () => resolve()); server!.kill(); }); } for (const suffix of ["", "-wal", "-shm"]) { const path = `${database}${suffix}`; if (existsSync(path)) rmSync(path); } }
