import Fastify, { type FastifyReply, type FastifyRequest } from "fastify";
import cors from "@fastify/cors";
import { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync } from "node:fs";
import { dirname, extname, isAbsolute, join, relative, resolve } from "node:path";
import type { ServerResponse } from "node:http";
import { advanceWorld, CHARACTER_CARDS, createWorld, createWorldV2, FIRST_WINTER_DILEMMAS, FIRST_WINTER_SCENARIO, HOME_SETTLEMENT, setObjectBlocked, type SocialInterpretation, type WorldEvent, type WorldState } from "@mimir/engine";
import { bundleHash, validateWorldBundle, type WorldBundle } from "@mimir/world-data";
import { normalizeState } from "./state.js";

const port = Number(process.env.PORT ?? 3000);
let tickIntervalMs = Number(process.env.TICK_INTERVAL_MS ?? 15000);
const autoTick = process.env.AUTO_TICK !== "false";
const seasonTickLimit = Number(process.env.SEASON_TICK_LIMIT ?? FIRST_WINTER_SCENARIO.seasonTickLimit);
const aiEnabled = process.env.AI_ENABLED === "true";
const socialBudgetCents = Number(process.env.SOCIAL_BUDGET_CENTS ?? 0);
const socialMode = aiEnabled && socialBudgetCents > 0 ? "ai-fallback" : "rules-only";
const ownerToken = process.env.OWNER_TOKEN;
const databasePath = process.env.DATABASE_PATH ?? "mimir.db";
const backupIntervalMs = Number(process.env.BACKUP_INTERVAL_MS ?? 0);
const backupDirectory = resolve(process.env.BACKUP_DIR ?? "backups");
const serveWeb = process.env.SERVE_WEB === "true";
const webDistDirectory = resolve(process.env.WEB_DIST_DIR ?? join(process.cwd(), "packages/web/dist"));
const worldBundleRoot = resolve(process.env.WORLD_BUNDLE_ROOT ?? join(process.cwd(), "assets/world/generated"));
const database = new DatabaseSync(databasePath);
database.exec("PRAGMA journal_mode = WAL;");
database.exec(`CREATE TABLE IF NOT EXISTS checkpoints (tick INTEGER PRIMARY KEY, state_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, tick INTEGER NOT NULL, event_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS interpretations (id TEXT PRIMARY KEY, tick INTEGER NOT NULL, interpretation_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS timelines (id TEXT PRIMARY KEY, parent_id TEXT, created_at TEXT NOT NULL, status TEXT NOT NULL, archived_at TEXT); CREATE TABLE IF NOT EXISTS timeline_checkpoints (timeline_id TEXT NOT NULL, tick INTEGER NOT NULL, state_json TEXT NOT NULL, PRIMARY KEY (timeline_id, tick)); CREATE TABLE IF NOT EXISTS timeline_events (timeline_id TEXT NOT NULL, id TEXT NOT NULL, tick INTEGER NOT NULL, event_json TEXT NOT NULL, PRIMARY KEY (timeline_id, id)); CREATE TABLE IF NOT EXISTS timeline_interpretations (timeline_id TEXT NOT NULL, id TEXT NOT NULL, tick INTEGER NOT NULL, interpretation_json TEXT NOT NULL, PRIMARY KEY (timeline_id, id)); CREATE TABLE IF NOT EXISTS pending_commands (id TEXT PRIMARY KEY, timeline_id TEXT NOT NULL, ordering INTEGER NOT NULL, target_tick INTEGER NOT NULL, settlement_id TEXT NOT NULL, object_id TEXT NOT NULL, blocked INTEGER NOT NULL, idempotency_key TEXT NOT NULL, status TEXT NOT NULL, result_json TEXT, created_at TEXT NOT NULL, UNIQUE(timeline_id, idempotency_key)); CREATE TABLE IF NOT EXISTS runtime_metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);`);
if (!database.prepare("SELECT id FROM timelines WHERE id = ?").get("main")) database.prepare("INSERT INTO timelines (id, parent_id, created_at, status) VALUES (?, NULL, ?, 'active')").run("main", new Date().toISOString());
const migrated = database.prepare("SELECT COUNT(*) AS count FROM timeline_checkpoints WHERE timeline_id = ?").get("main") as { count: number };
if (migrated.count === 0) {
  database.exec("INSERT INTO timeline_checkpoints (timeline_id, tick, state_json) SELECT 'main', tick, state_json FROM checkpoints;");
  database.exec("INSERT INTO timeline_events (timeline_id, id, tick, event_json) SELECT 'main', id, tick, event_json FROM events;");
  database.exec("INSERT INTO timeline_interpretations (timeline_id, id, tick, interpretation_json) SELECT 'main', id, tick, interpretation_json FROM interpretations;");
}
const savedTimeline = database.prepare("SELECT value FROM runtime_metadata WHERE key = 'active_timeline'").get() as { value: string } | undefined;
let activeTimelineId = savedTimeline?.value ?? "main";
let schedulerPaused = !autoTick;
let scheduler: NodeJS.Timeout | undefined;
let shuttingDown = false;
function createScheduledBackup(reason: string) {
  if (!existsSync(databasePath)) return;
  const database = new DatabaseSync(databasePath);
  database.exec("PRAGMA wal_checkpoint(FULL);");
  database.close();
  mkdirSync(dirname(join(backupDirectory, "placeholder")), { recursive: true });
  const destination = join(backupDirectory, `mimir-${new Date().toISOString().replaceAll(":", "-")}-${reason}.db`);
  copyFileSync(databasePath, destination);
  app.log.info({ destination }, "scheduled database backup created");
}

function loadState(timelineId: string): WorldState {
  const row = database.prepare("SELECT state_json FROM timeline_checkpoints WHERE timeline_id = ? ORDER BY tick DESC LIMIT 1").get(timelineId) as { state_json: string } | undefined;
  return normalizeState(row ? JSON.parse(row.state_json) as WorldState : createWorld(20260906, timelineId));
}
let state = loadState(activeTimelineId);
if (!database.prepare("SELECT 1 FROM timeline_checkpoints WHERE timeline_id = ? LIMIT 1").get(activeTimelineId)) database.prepare("INSERT INTO timeline_checkpoints (timeline_id, tick, state_json) VALUES (?, ?, ?)").run(activeTimelineId, state.tick, JSON.stringify(state));
database.prepare("INSERT INTO runtime_metadata (key, value) VALUES ('active_timeline', ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value").run(activeTimelineId);
const liveClients = new Set<ServerResponse>();
const app = Fastify({ logger: true });
await app.register(cors, { origin: true });
function requireOwner(request: FastifyRequest, reply: FastifyReply): boolean { if (!ownerToken || request.headers["x-owner-token"] === ownerToken) return true; reply.code(401).send({ error: "owner authorization required" }); return false; }
function currentTimeline() { return database.prepare("SELECT id, parent_id, created_at, status, archived_at FROM timelines WHERE id = ?").get(activeTimelineId) as { id: string; parent_id: string | null; created_at: string; status: string; archived_at: string | null }; }
function saveActiveTimeline() { database.prepare("INSERT INTO runtime_metadata (key, value) VALUES ('active_timeline', ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value").run(activeTimelineId); }
type PendingBlockCommand = { id: string; ordering: number; target_tick: number; settlement_id: string; object_id: string; blocked: number; idempotency_key: string; status: string; result_json: string | null };
function currentObjectFootprint(objectId: string): Set<string> { const world = state.worldDefinition; if (world) { const object = world.objects.find(candidate => candidate.id === objectId); if (!object) return new Set(); const definition = world.definitions[object.definitionId]; return new Set(definition.footprint.map(offset => `${object.position.x + offset.x},${object.position.y + offset.y}`)); } const structured = state.structuredState?.settlements.flatMap(settlement => settlement.bundle.objects.map(object => ({ settlement, object }))).find(candidate => candidate.object.id === objectId); if (!structured) return new Set(); const definition = structured.settlement.bundle.objectDefinitions[structured.object.definitionId]; return new Set(definition.footprint.map(offset => `${structured.object.origin.x + offset.x},${structured.object.origin.y + offset.y}`)); }
function occupiedActorIds(objectId: string): string[] { const footprint = currentObjectFootprint(objectId); return state.villagers.filter(villager => footprint.has(`${villager.position.x},${villager.position.y}`)).map(villager => villager.id).sort(); }
function pendingCommandsForTick(tick: number): PendingBlockCommand[] { return database.prepare("SELECT id, ordering, target_tick, settlement_id, object_id, blocked, idempotency_key, status, result_json FROM pending_commands WHERE timeline_id = ? AND status = 'pending' AND target_tick <= ? ORDER BY ordering ASC").all(activeTimelineId, tick) as PendingBlockCommand[]; }
function applyPendingCommands(base: WorldState, tick: number): { state: WorldState; events: WorldEvent[]; commands: PendingBlockCommand[] } { let next = base; const events: WorldEvent[] = []; const commands = pendingCommandsForTick(tick); for (const command of commands) { const occupied = command.blocked ? occupiedActorIds(command.object_id) : []; if (occupied.length) { events.push({ id: `event-${tick}-command-${command.id}`, tick, kind: "world-object", message: `Object ${command.object_id} could not be blocked because it contains actors: ${occupied.join(", ")}.`, villagerIds: occupied, settlementIds: [command.settlement_id] }); continue; } if (next.structuredState) { const structuredState = structuredClone(next.structuredState); const settlement = structuredState.settlements.find(candidate => candidate.id === command.settlement_id); const object = settlement?.bundle.objects.find(candidate => candidate.id === command.object_id); if (!settlement || !object) continue; const current = settlement.runtime.objects.find(item => item.objectId === command.object_id); const previousBlocked = current?.blocked ?? false; if (previousBlocked !== Boolean(command.blocked)) { if (current) current.blocked = Boolean(command.blocked); else settlement.runtime.objects.push({ objectId: command.object_id, blocked: Boolean(command.blocked) }); settlement.runtime.navigationRevision += 1; } next = { ...next, structuredState, worldRuntime: { ...(next.worldRuntime ?? { blockedObjectIds: [] }), blockedObjectIds: command.blocked ? [...new Set([...(next.worldRuntime?.blockedObjectIds ?? []), command.object_id])] : (next.worldRuntime?.blockedObjectIds ?? []).filter(id => id !== command.object_id) } }; if (previousBlocked !== Boolean(command.blocked)) events.push({ id: `event-${tick}-command-${command.id}`, tick, kind: "world-object", message: `Object ${command.object_id} is now ${command.blocked ? "blocked" : "open"}.`, villagerIds: [], settlementIds: [command.settlement_id] }); continue; } const before = next.worldRuntime?.blockedObjectIds ?? []; const after = setObjectBlocked(next.worldDefinition!, next.worldRuntime ?? { blockedObjectIds: [] }, command.object_id, Boolean(command.blocked)).blockedObjectIds; const changed = before.join(",") !== after.join(","); next = { ...next, worldRuntime: { ...(next.worldRuntime ?? { blockedObjectIds: [] }), blockedObjectIds: after }, settlements: next.settlements.map(settlement => settlement.id === command.settlement_id ? { ...settlement, worldRuntime: { ...settlement.worldRuntime, blockedObjectIds: after } } : settlement) }; if (changed) events.push({ id: `event-${tick}-command-${command.id}`, tick, kind: "world-object", message: `Object ${command.object_id} is now ${command.blocked ? "blocked" : "open"}.`, villagerIds: [], settlementIds: [command.settlement_id] }); } return { state: next, events, commands }; }

app.get("/health", async () => ({ ok: true, tick: state.tick, schedulerPaused, databasePath, timeline: currentTimeline(), socialMode, socialBudgetCents }));
app.get("/api/social/config", async () => ({ mode: socialMode, aiEnabled, budgetCents: socialBudgetCents, provider: "none", historicalPlaybackUsesAI: false }));
app.get("/api/design", async () => ({ characterCards: CHARACTER_CARDS, dilemmas: FIRST_WINTER_DILEMMAS, sharedStore: state.sharedStore }));
app.get("/api/region", async () => ({ settlements: state.settlements, routes: state.routes, tradeHistory: state.tradeHistory, weather: state.weather, hazards: state.hazards, timelineId: activeTimelineId }));
app.get("/api/timelines", async () => ({ activeTimelineId, timelines: database.prepare("SELECT id, parent_id, created_at, status, archived_at FROM timelines ORDER BY created_at").all() }));
app.get("/api/world/bundles/:hash", async (request, reply) => { const hash = (request.params as { hash?: string }).hash; if (!hash || !/^sha256-[a-f0-9]{64}$/.test(hash)) return reply.code(400).send({ error: "invalid bundle hash" }); const bundlePath = resolve(worldBundleRoot, hash, "world.json"); const relativeBundlePath = relative(worldBundleRoot, bundlePath); if (relativeBundlePath.startsWith("..") || isAbsolute(relativeBundlePath) || !existsSync(bundlePath)) return reply.code(404).send({ error: "bundle not found" }); try { const bundle = JSON.parse(readFileSync(bundlePath, "utf8")) as WorldBundle; validateWorldBundle(bundle); if (bundleHash(bundle) !== hash) return reply.code(409).send({ error: "bundle content hash mismatch" }); return { bundle }; } catch (error) { return reply.code(409).send({ error: error instanceof Error ? error.message : "invalid bundle" }); } });
app.get("/api/live", async (_request, reply) => { reply.hijack(); const response = reply.raw; response.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive", "access-control-allow-origin": "*" }); response.write(`data: ${JSON.stringify({ state, timelineId: activeTimelineId, schedulerPaused })}\n\n`); liveClients.add(response); response.on("close", () => liveClients.delete(response)); });
app.get("/api/world", async (request, reply) => { const query = request.query as { tick?: string }; if (query.tick === undefined) return { state, timelineId: activeTimelineId, schedulerPaused }; const tick = Number(query.tick); if (!Number.isInteger(tick) || tick < 0) return reply.code(400).send({ error: "tick must be a non-negative integer" }); const row = database.prepare("SELECT state_json FROM timeline_checkpoints WHERE timeline_id = ? AND tick = ?").get(activeTimelineId, tick) as { state_json: string } | undefined; if (!row) return reply.code(404).send({ error: `No checkpoint exists for tick ${tick}` }); return { state: normalizeState(JSON.parse(row.state_json) as WorldState), timelineId: activeTimelineId, schedulerPaused }; });
app.get("/api/events", async (request) => { const query = request.query as { limit?: string }; const limit = Math.min(200, Math.max(1, Number(query.limit ?? 50))); const rows = database.prepare("SELECT event_json FROM timeline_events WHERE timeline_id = ? ORDER BY tick DESC LIMIT ?").all(activeTimelineId, limit) as { event_json: string }[]; return { events: rows.reverse().map((row) => JSON.parse(row.event_json) as WorldEvent[]).flat(), timelineId: activeTimelineId }; });
app.get("/api/interpretations", async (request) => { const query = request.query as { limit?: string }; const limit = Math.min(200, Math.max(1, Number(query.limit ?? 50))); const rows = database.prepare("SELECT interpretation_json FROM timeline_interpretations WHERE timeline_id = ? ORDER BY tick DESC LIMIT ?").all(activeTimelineId, limit) as { interpretation_json: string }[]; return { interpretations: rows.reverse().map((row) => JSON.parse(row.interpretation_json) as SocialInterpretation), timelineId: activeTimelineId }; });
app.get("/api/metrics", async () => {
  const rows = database.prepare("SELECT tick, state_json FROM timeline_checkpoints WHERE timeline_id = ? ORDER BY tick ASC").all(activeTimelineId) as { tick: number; state_json: string }[];
  return {
    timelineId: activeTimelineId,
    metrics: rows.map((row) => {
      const snapshot = normalizeState(JSON.parse(row.state_json) as WorldState);
      return {
        tick: row.tick,
        foodReserve: snapshot.foodReserve,
        averageTrust: Math.round(snapshot.villagers.reduce((total, villager) => total + villager.trust, 0) / snapshot.villagers.length),
        hungryVillagers: snapshot.villagers.filter((villager) => villager.hunger >= 45).length,
        travelingVillagers: snapshot.villagers.filter((villager) => villager.activity === "travel").length,
        collectingVillagers: snapshot.villagers.filter((villager) => villager.activity === "collect").length
      };
    })
  };
});
app.get("/api/report", async () => { const timeline = currentTimeline(); const counts = database.prepare("SELECT (SELECT COUNT(*) FROM timeline_checkpoints WHERE timeline_id = ?) AS checkpoints, (SELECT COUNT(*) FROM timeline_events WHERE timeline_id = ?) AS events, (SELECT COUNT(*) FROM timeline_interpretations WHERE timeline_id = ?) AS interpretations").get(activeTimelineId, activeTimelineId, activeTimelineId) as { checkpoints: number; events: number; interpretations: number }; const averageTrust = Math.round(state.villagers.reduce((total, villager) => total + villager.trust, 0) / state.villagers.length); const dilemmas = state.dilemmaHistory ?? []; return { timeline, tick: state.tick, schedulerPaused, tickIntervalMs, databaseBytes: existsSync(databasePath) ? statSync(databasePath).size : 0, socialMode, socialBudgetCents, fallbackCount: counts.interpretations, summary: { season: state.season, scenarioName: state.scenario.name, finalFood: state.foodReserve, averageTrust, villagers: state.villagers.length, dilemmasResolved: dilemmas.length, latestDilemma: dilemmas.at(-1) ?? null }, ...counts }; });
app.post("/api/scheduler", async (request, reply) => { if (!requireOwner(request, reply)) return; const body = request.body as { paused?: unknown; intervalMs?: unknown } | undefined; if (body?.paused !== undefined && typeof body.paused !== "boolean") return reply.code(400).send({ error: "paused must be a boolean" }); if (body?.intervalMs !== undefined && (!Number.isInteger(body.intervalMs) || Number(body.intervalMs) < 250 || Number(body.intervalMs) > 300000)) return reply.code(400).send({ error: "intervalMs must be an integer between 250 and 300000" }); if (typeof body?.intervalMs === "number") tickIntervalMs = body.intervalMs; if (typeof body?.paused === "boolean") schedulerPaused = body.paused; restartScheduler(); return { schedulerPaused, tickIntervalMs }; });
app.post("/api/owner/world/object", async (request, reply) => { if (!requireOwner(request, reply)) return; const body = request.body as { settlementId?: unknown; objectId?: unknown; blocked?: unknown; idempotencyKey?: unknown } | undefined; if (typeof body?.objectId !== "string" || typeof body.blocked !== "boolean" || typeof body.idempotencyKey !== "string" || body.idempotencyKey.length === 0) return reply.code(400).send({ error: "settlementId, objectId, blocked, and idempotencyKey are required" }); const settlementId = typeof body.settlementId === "string" ? body.settlementId : HOME_SETTLEMENT.id; const existing = database.prepare("SELECT id, ordering, target_tick, settlement_id, object_id, blocked, idempotency_key, status, result_json FROM pending_commands WHERE timeline_id = ? AND idempotency_key = ?").get(activeTimelineId, body.idempotencyKey) as PendingBlockCommand | undefined; if (existing) return reply.code(existing.status === "rejected" ? 409 : 202).send(existing.result_json ? JSON.parse(existing.result_json) : { commandId: existing.id, effectiveTick: existing.target_tick, status: existing.status }); try { if (!state.worldDefinition || !state.worldDefinition.objects.some(object => object.id === body.objectId)) return reply.code(400).send({ error: `unknown world object: ${body.objectId}` }); if (!state.settlements.some(settlement => settlement.id === settlementId)) return reply.code(400).send({ error: `unknown settlement: ${settlementId}` }); const occupied = body.blocked ? occupiedActorIds(body.objectId) : []; if (occupied.length) return reply.code(409).send({ error: "blocking would cover occupied cells", actorIds: occupied }); const id = `command-${randomUUID()}`; const ordering = Number((database.prepare("SELECT COALESCE(MAX(ordering), 0) AS ordering FROM pending_commands WHERE timeline_id = ?").get(activeTimelineId) as { ordering: number }).ordering) + 1; const targetTick = state.tick + 1; const result = { commandId: id, effectiveTick: targetTick, status: "pending", objectId: body.objectId, blocked: body.blocked, idempotencyKey: body.idempotencyKey }; database.prepare("INSERT INTO pending_commands (id, timeline_id, ordering, target_tick, settlement_id, object_id, blocked, idempotency_key, status, result_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)").run(id, activeTimelineId, ordering, targetTick, settlementId, body.objectId, body.blocked ? 1 : 0, body.idempotencyKey, JSON.stringify(result), new Date().toISOString()); return reply.code(202).send(result); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : "invalid world object command" }); } });

function commitTick(): { state: WorldState; events: WorldEvent[]; interpretations: SocialInterpretation[] } | null {
  if (state.tick >= seasonTickLimit || currentTimeline().status !== "active") return null;
  const pending = applyPendingCommands(state, state.tick + 1);
  const advanced = advanceWorld(pending.state);
  const result = { ...advanced, events: [...pending.events, ...advanced.events] };
  database.exec("BEGIN IMMEDIATE");
  try {
    database.prepare("INSERT INTO timeline_checkpoints (timeline_id, tick, state_json) VALUES (?, ?, ?)").run(activeTimelineId, result.state.tick, JSON.stringify(result.state));
    const insertEvent = database.prepare("INSERT INTO timeline_events (timeline_id, id, tick, event_json) VALUES (?, ?, ?, ?)");
    for (const event of result.events) insertEvent.run(activeTimelineId, event.id, event.tick, JSON.stringify(event));
    const updateCommand = database.prepare("UPDATE pending_commands SET status = ?, result_json = ? WHERE id = ? AND status = 'pending'");
    for (const command of pending.commands) { const rejected = pending.events.some(event => event.id === `event-${result.state.tick}-command-${command.id}` && event.message.includes("could not")); updateCommand.run(rejected ? "rejected" : "applied", JSON.stringify({ commandId: command.id, effectiveTick: result.state.tick, status: rejected ? "rejected" : "applied", objectId: command.object_id, blocked: Boolean(command.blocked), idempotencyKey: command.idempotency_key }), command.id); }
    const insertInterpretation = database.prepare("INSERT INTO timeline_interpretations (timeline_id, id, tick, interpretation_json) VALUES (?, ?, ?, ?)");
    for (const interpretation of result.interpretations) insertInterpretation.run(activeTimelineId, interpretation.id, interpretation.tick, JSON.stringify(interpretation));
    database.exec("COMMIT");
  } catch (error) { database.exec("ROLLBACK"); throw error; }
  state = result.state;
  const message = `data: ${JSON.stringify({ state, events: result.events, interpretations: result.interpretations, timelineId: activeTimelineId, schedulerPaused })}\n\n`;
  for (const client of liveClients) { if (!client.destroyed) client.write(message); else liveClients.delete(client); }
  return result;
}
app.post("/api/tick", async (request, reply) => { if (!requireOwner(request, reply)) return; const result = commitTick(); if (!result) return reply.code(409).send({ error: "timeline is archived or season boundary reached", state }); return result; });
app.post("/api/owner/archive", async (request, reply) => { if (!requireOwner(request, reply)) return; database.prepare("UPDATE timelines SET status = 'archived', archived_at = ? WHERE id = ?").run(new Date().toISOString(), activeTimelineId); schedulerPaused = true; return { timeline: currentTimeline(), schedulerPaused }; });
app.post("/api/owner/continue", async (request, reply) => { if (!requireOwner(request, reply)) return; database.prepare("UPDATE timelines SET status = 'active', archived_at = NULL WHERE id = ?").run(activeTimelineId); return { timeline: currentTimeline(), schedulerPaused }; });
app.post("/api/owner/branch", async (request, reply) => { if (!requireOwner(request, reply)) return; const body = request.body as { tick?: unknown } | undefined; const branchTick = body?.tick === undefined ? state.tick : Number(body.tick); if (!Number.isInteger(branchTick) || branchTick < 0) return reply.code(400).send({ error: "tick must be a non-negative integer" }); const source = database.prepare("SELECT state_json FROM timeline_checkpoints WHERE timeline_id = ? AND tick = ?").get(activeTimelineId, branchTick) as { state_json: string } | undefined; if (!source) return reply.code(404).send({ error: "branch source checkpoint not found" }); const newId = `timeline-${randomUUID()}`; database.exec("BEGIN IMMEDIATE"); try { database.prepare("INSERT INTO timelines (id, parent_id, created_at, status) VALUES (?, ?, ?, 'active')").run(newId, activeTimelineId, new Date().toISOString()); database.prepare("INSERT INTO timeline_checkpoints (timeline_id, tick, state_json) SELECT ?, tick, state_json FROM timeline_checkpoints WHERE timeline_id = ? AND tick <= ?").run(newId, activeTimelineId, branchTick); database.prepare("INSERT INTO timeline_events (timeline_id, id, tick, event_json) SELECT ?, id, tick, event_json FROM timeline_events WHERE timeline_id = ? AND tick <= ?").run(newId, activeTimelineId, branchTick); database.prepare("INSERT INTO timeline_interpretations (timeline_id, id, tick, interpretation_json) SELECT ?, id, tick, interpretation_json FROM timeline_interpretations WHERE timeline_id = ? AND tick <= ?").run(newId, activeTimelineId, branchTick); database.exec("COMMIT"); } catch (error) { database.exec("ROLLBACK"); throw error; } activeTimelineId = newId; state = { ...normalizeState(JSON.parse(source.state_json) as WorldState), worldId: newId }; saveActiveTimeline(); return { timeline: currentTimeline(), state }; });
app.post("/api/owner/reset", async (request, reply) => { if (!requireOwner(request, reply)) return; const body = request.body as { seed?: unknown } | undefined; const seed = body?.seed === undefined ? 20260906 : Number(body.seed); if (!Number.isInteger(seed)) return reply.code(400).send({ error: "seed must be an integer" }); const parent = activeTimelineId; database.prepare("UPDATE timelines SET status = 'archived', archived_at = ? WHERE id = ?").run(new Date().toISOString(), parent); activeTimelineId = `timeline-${randomUUID()}`; state = createWorld(seed, activeTimelineId); database.prepare("INSERT INTO timelines (id, parent_id, created_at, status) VALUES (?, ?, ?, 'active')").run(activeTimelineId, parent, new Date().toISOString()); database.prepare("INSERT INTO timeline_checkpoints (timeline_id, tick, state_json) VALUES (?, 0, ?)").run(activeTimelineId, JSON.stringify(state)); schedulerPaused = true; saveActiveTimeline(); return { timeline: currentTimeline(), state, schedulerPaused }; });

app.post("/api/owner/reset-v2", async (request, reply) => { if (!requireOwner(request, reply)) return; const body = request.body as { bundleHash?: unknown; seed?: unknown } | undefined; if (typeof body?.bundleHash !== "string" || !/^sha256-[a-f0-9]{64}$/.test(body.bundleHash)) return reply.code(400).send({ error: "bundleHash is required" }); const bundlePath = resolve(worldBundleRoot, body.bundleHash, "world.json"); const relativeBundlePath = relative(worldBundleRoot, bundlePath); if (relativeBundlePath.startsWith("..") || isAbsolute(relativeBundlePath) || !existsSync(bundlePath)) return reply.code(404).send({ error: "bundle not found" }); try { const bundle = JSON.parse(readFileSync(bundlePath, "utf8")) as WorldBundle; validateWorldBundle(bundle); if (bundleHash(bundle) !== body.bundleHash) return reply.code(409).send({ error: "bundle content hash mismatch" }); const seed = body.seed === undefined ? 20260906 : Number(body.seed); if (!Number.isInteger(seed)) return reply.code(400).send({ error: "seed must be an integer" }); const parent = activeTimelineId; database.prepare("UPDATE timelines SET status = 'archived', archived_at = ? WHERE id = ?").run(new Date().toISOString(), parent); activeTimelineId = `timeline-${randomUUID()}`; state = createWorldV2(bundle, seed, activeTimelineId); database.prepare("INSERT INTO timelines (id, parent_id, created_at, status) VALUES (?, ?, ?, 'active')").run(activeTimelineId, parent, new Date().toISOString()); database.prepare("INSERT INTO timeline_checkpoints (timeline_id, tick, state_json) VALUES (?, 0, ?)").run(activeTimelineId, JSON.stringify(state)); schedulerPaused = true; saveActiveTimeline(); return { timeline: currentTimeline(), state, schedulerPaused, bundleHash: body.bundleHash }; } catch (error) { return reply.code(409).send({ error: error instanceof Error ? error.message : "invalid bundle" }); } });

if (serveWeb) {
  app.get("/*", async (request, reply) => {
    const requestedPath = decodeURIComponent((request.raw.url ?? "/").split("?", 1)[0]);
    if (requestedPath.startsWith("/api/") || requestedPath === "/health") return reply.code(404).send({ error: "not found" });
    const relativePath = requestedPath === "/" ? "index.html" : requestedPath.replace(/^\/+/, "");
    const candidate = resolve(webDistDirectory, relativePath);
    const safePath = relative(candidate, webDistDirectory);
    const safe = safePath === "" || (!safePath.startsWith("..") && !isAbsolute(safePath));
    const indexPath = join(webDistDirectory, "index.html");
    const filePath = safe && existsSync(candidate) && statSync(candidate).isFile() ? candidate : indexPath;
    if (!existsSync(filePath)) return reply.code(404).send({ error: "web build not found" });
    const contentTypes: Record<string, string> = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg", ".webp": "image/webp" };
    return reply.type(contentTypes[extname(filePath)] ?? "application/octet-stream").send(readFileSync(filePath));
  });
}

await app.listen({ port, host: "0.0.0.0" });
function restartScheduler() { if (scheduler) clearInterval(scheduler); if (tickIntervalMs > 0) { scheduler = setInterval(() => { if (!shuttingDown && !schedulerPaused && state.tick < seasonTickLimit) commitTick(); }, tickIntervalMs); scheduler.unref(); } }
restartScheduler();
app.log.info({ tickIntervalMs, seasonTickLimit, schedulerPaused }, "automatic tick scheduler configured");
let backupScheduler: NodeJS.Timeout | undefined;
if (backupIntervalMs > 0) { backupScheduler = setInterval(() => { if (!shuttingDown) createScheduledBackup("interval"); }, backupIntervalMs); backupScheduler.unref(); app.log.info({ backupIntervalMs, backupDirectory }, "scheduled database backups configured"); }
async function shutdown(signal: string) { if (shuttingDown) return; shuttingDown = true; if (scheduler) clearInterval(scheduler); if (backupScheduler) clearInterval(backupScheduler); for (const client of liveClients) client.end(); await app.close(); database.exec("PRAGMA wal_checkpoint(FULL);"); database.close(); app.log.info({ signal, tick: state.tick, timelineId: activeTimelineId }, "server shut down cleanly"); process.exit(0); }
process.once("SIGINT", () => void shutdown("SIGINT"));
process.once("SIGTERM", () => void shutdown("SIGTERM"));
