import type { Cell, WorldBundle, WorldRuntimeState } from "./types.js";
export type BlockReason = "out-of-bounds" | "terrain" | "solid-object" | "runtime-blocker";
export type CellQuery = { walkable: true; cost: number } | { walkable: false; reason: BlockReason; objectId?: string };
const key = (cell: Cell) => `${cell.x},${cell.y}`;
const same = (a: Cell, b: Cell) => a.x === b.x && a.y === b.y;
function objectCells(world: WorldBundle, objectId: string) { const object = world.objects.find(o => o.id === objectId)!; return world.objectDefinitions[object.definitionId].footprint.map(offset => ({ x: object.origin.x + offset.x, y: object.origin.y + offset.y })); }
export function queryCell(world: WorldBundle, runtime: WorldRuntimeState, cell: Cell): CellQuery { if (!Number.isInteger(cell.x) || !Number.isInteger(cell.y) || cell.x < 0 || cell.y < 0 || cell.x >= world.width || cell.y >= world.height) return { walkable: false, reason: "out-of-bounds" }; for (const object of world.objects) { const definition = world.objectDefinitions[object.definitionId]; if ((definition.blocksMovement || runtime.objects.some(o => o.objectId === object.id && o.blocked)) && objectCells(world, object.id).some(c => same(c, cell))) return { walkable: false, reason: runtime.objects.some(o => o.objectId === object.id && o.blocked) ? "runtime-blocker" : "solid-object", objectId: object.id }; } const surface = world.surfaces.find(s => s.enabled && s.cells.some(c => same(c, cell))); if (surface) return { walkable: true, cost: surface.movementCost }; const terrain = world.terrainDefinitions[world.terrain[cell.y][cell.x]]; return terrain.walkable ? { walkable: true, cost: terrain.movementCost! } : { walkable: false, reason: "terrain" }; }
export function canTraverse(world: WorldBundle, runtime: WorldRuntimeState, from: Cell, to: Cell): CellQuery | { walkable: false; reason: "non-adjacent" } { if (Math.abs(from.x - to.x) + Math.abs(from.y - to.y) !== 1) return { walkable: false, reason: "non-adjacent" }; const start = queryCell(world, runtime, from); if (!start.walkable) return start; return queryCell(world, runtime, to); }
export function validateCardinalRoute(world: WorldBundle, runtime: WorldRuntimeState, route: Cell[]): void { if (route.length === 0) throw new Error("route must contain a start cell"); for (let i = 0; i < route.length; i++) { const q = queryCell(world, runtime, route[i]); if (!q.walkable) throw new Error(`route cell ${key(route[i])} is blocked: ${q.reason}`); if (i > 0) { const edge = canTraverse(world, runtime, route[i - 1], route[i]); if (!edge.walkable) throw new Error(`route edge ${key(route[i - 1])}->${key(route[i])} is blocked: ${edge.reason}`); } } }
