import { FIRST_GLOW_AGE_ID, FIRST_GLOW_SIMULATION_VERSION, FIRST_GLOW_WORLD_SCHEMA_VERSION, LIVING_CIRCUIT_THEME_ID, type Cell, type DecodedWorldBundle, type ObjectDefinition, type WorldBundle, type WorldRuntimeState } from "./types.js";
import { bundleHash } from "./canonical.js";
import { canTraverse, queryCell } from "./spatial.js";

const fail = (message: string): never => { throw new Error(message); };
function assert(condition: unknown, message: string): asserts condition { if (!condition) fail(message); }
function validateCell(cell: unknown, label: string, world: DecodedWorldBundle): asserts cell is Cell { assert(cell && typeof cell === "object" && !Array.isArray(cell), `${label} must be an object`); const c = cell as Cell; assert(Number.isInteger(c.x) && Number.isInteger(c.y), `${label} must use integer coordinates`); assert(c.x >= 0 && c.y >= 0 && c.x < world.width && c.y < world.height, `${label} is out of bounds at ${c.x},${c.y}`); }
function validateOffsets(offsets: Cell[], label: string) { const seen = new Set<string>(); for (const cell of offsets) { assert(Number.isInteger(cell.x) && Number.isInteger(cell.y), `${label} contains a non-integer offset`); const key = `${cell.x},${cell.y}`; assert(!seen.has(key), `${label} contains duplicate offset ${key}`); seen.add(key); } }
function validateDefinition(definition: ObjectDefinition) { assert(definition.id.length > 0, "object definition id is empty"); validateOffsets(definition.footprint, `${definition.id}.footprint`); const slots = new Set<string>(); for (const slot of definition.slots) { assert(slot.id.length > 0 && !slots.has(slot.id), `${definition.id} has duplicate slot id`); slots.add(slot.id); validateOffsets([slot.offset], `${definition.id}.${slot.id}`); } assert(Number.isInteger(definition.capacity) && definition.capacity >= 0 && definition.capacity <= Math.max(0, definition.slots.length), `${definition.id} has invalid capacity`); if (definition.capabilities.length === 0) assert(definition.capacity === 0, `${definition.id} has capacity without capabilities`); }
export function validateWorldBundle(world: DecodedWorldBundle): void {
  assert(world && typeof world === "object" && !Array.isArray(world), "world bundle must be an object"); const firstGlow = world.schemaVersion === FIRST_GLOW_WORLD_SCHEMA_VERSION;
  assert(firstGlow && world.spatialModel === "structured-v2" && world.simulationVersion === FIRST_GLOW_SIMULATION_VERSION && world.themeId === LIVING_CIRCUIT_THEME_ID && world.ageId === FIRST_GLOW_AGE_ID, "unsupported world bundle version/theme");
  assert(typeof world.id === "string" && world.id.length > 0, "world id is required"); assert(Number.isInteger(world.width) && world.width > 0 && Number.isInteger(world.height) && world.height > 0, "invalid world dimensions"); assert(world.cellSizePx === 24, "unsupported cell size"); assert(Array.isArray(world.terrain) && world.terrainDefinitions && typeof world.terrainDefinitions === "object" && Array.isArray(world.surfaces) && world.objectDefinitions && typeof world.objectDefinitions === "object" && Array.isArray(world.objects) && Array.isArray(world.layers) && Array.isArray(world.spawns) && Array.isArray(world.assets) && world.bundle && typeof world.bundle === "object", "world bundle has malformed nested data");
  assert(world.terrain.length === world.height && world.terrain.every(row => Array.isArray(row) && row.length === world.width && row.every(id => typeof id === "string")), "terrain dimensions or cell types are invalid"); for (const row of world.terrain) for (const id of row) assert(world.terrainDefinitions[id], `unknown terrain ${id}`); for (const terrain of Object.values(world.terrainDefinitions)) { assert(terrain && typeof terrain.id === "string" && typeof terrain.walkable === "boolean", "malformed terrain definition"); if (!terrain.walkable) continue; const movementCost = terrain.movementCost; if (typeof movementCost !== "number" || !Number.isInteger(movementCost) || movementCost <= 0) fail(`terrain ${terrain.id} has invalid movement cost`); }
  const objectIds = new Set<string>(); for (const object of world.objects) { assert(object && typeof object.id === "string" && typeof object.definitionId === "string" && object.id.length > 0 && !objectIds.has(object.id), `duplicate or empty object id ${object?.id ?? ""}`); objectIds.add(object.id); assert(object.definitionId in world.objectDefinitions, `unknown object definition ${object.definitionId}`); assert(object.orientation === 0, `unsupported orientation for ${object.id}`); validateCell(object.origin, `object ${object.id}`, world); }
  for (const definition of Object.values(world.objectDefinitions)) { validateDefinition(definition); if (firstGlow) { const candidate = definition as ObjectDefinition & { label?: unknown }; assert(typeof candidate.label === "string" && candidate.label.length > 0, `First Glow definition ${definition.id} needs a display label`); assert(definition.capabilities.every(capability => ["charge-pool", "shelter-niche", "trace", "relay-crossing", "pattern-shard", "light-mark"].includes(capability)), `unknown First Glow capability on ${definition.id}`); } } for (const surface of world.surfaces) { assert(surface && typeof surface.id === "string" && Array.isArray(surface.cells), "malformed surface"); assert(Number.isInteger(surface.movementCost) && surface.movementCost > 0 && typeof surface.enabled === "boolean", `surface ${surface.id} has invalid fields`); for (const cell of surface.cells) validateCell(cell, `surface ${surface.id}`, world); }
  const spawnIds = new Set<string>(); for (const spawn of world.spawns) { assert(spawn && typeof spawn.id === "string" && typeof spawn.settlementId === "string" && !spawnIds.has(spawn.id) && spawn.id.length > 0, `duplicate or empty spawn id ${spawn?.id ?? ""}`); spawnIds.add(spawn.id); validateCell(spawn.cell, `spawn ${spawn.id}`, world); }
  const assetPaths = new Set<string>(); for (const asset of world.assets) { assert(asset && typeof asset.path === "string" && typeof asset.sha256 === "string" && typeof asset.mediaType === "string" && typeof asset.version === "string" && asset.path.length > 0, "malformed asset manifest entry"); assert(!assetPaths.has(asset.path), `duplicate asset path ${asset.path}`); assetPaths.add(asset.path); }
  const layerIds = new Set<string>(); for (const layer of world.layers) { assert(layer && typeof layer.id === "string" && typeof layer.order === "number" && ["ground", "surface", "objects", "foreground", "spawns"].includes(layer.role), "malformed layer"); assert(!layerIds.has(layer.id), `duplicate layer id ${layer.id}`); layerIds.add(layer.id); }
  assert(world.bundle?.schemaVersion === world.schemaVersion && world.bundle.contentHash === bundleHash(world), "world bundle content hash does not match definition");
  validateAuthoredSpatialContent(world);
}
export function validateRuntimeState(world: DecodedWorldBundle, runtime: WorldRuntimeState, actorIds?: Iterable<string>): void { assert(runtime && typeof runtime === "object", "runtime state must be an object"); assert(Number.isInteger(runtime.navigationRevision) && runtime.navigationRevision >= 0, "invalid navigation revision"); assert(Array.isArray(runtime.objects) && Array.isArray(runtime.reservations), "runtime collections are required"); const objects = new Set(world.objects.map(o => o.id)); const slots = new Set(world.objects.flatMap(o => (world.objectDefinitions[o.definitionId]?.slots ?? []).map(s => `${o.id}:${s.id}`))); const knownActors = actorIds ? new Set(actorIds) : undefined; const seenObjects = new Set<string>(); const seen = new Set<string>(); for (const state of runtime.objects) { assert(state && typeof state === "object" && typeof state.objectId === "string", "malformed runtime object"); assert(objects.has(state.objectId), `runtime references unknown object ${state.objectId}`); assert(typeof state.blocked === "boolean", `runtime blocker ${state.objectId} has invalid blocked state`); assert(!seenObjects.has(state.objectId), `duplicate runtime object ${state.objectId}`); seenObjects.add(state.objectId); } for (const reservation of runtime.reservations) { assert(reservation && typeof reservation === "object" && typeof reservation.actorId === "string" && typeof reservation.objectId === "string" && typeof reservation.slotId === "string", "malformed reservation"); const key = `${reservation.objectId}:${reservation.slotId}`; assert(reservation.actorId.length > 0, "runtime reservation actor is empty"); assert(!knownActors || knownActors.has(reservation.actorId), `runtime reservation references unknown actor ${reservation.actorId}`); assert(slots.has(key), `runtime references unknown slot ${key}`); assert(!seen.has(key), `duplicate reservation ${key}`); seen.add(key); } }

export function decodeWorldBundle(raw: unknown): DecodedWorldBundle { assert(raw && typeof raw === "object" && !Array.isArray(raw), "world bundle must be an object"); const schemaVersion = (raw as { schemaVersion?: unknown }).schemaVersion; assert(schemaVersion === FIRST_GLOW_WORLD_SCHEMA_VERSION, "unsupported world bundle schema"); const world = raw as DecodedWorldBundle; validateWorldBundle(world); return world; }

export function validateAuthoredSpatialContent(world: DecodedWorldBundle): void {
  const runtime: WorldRuntimeState = { navigationRevision: 0, objects: [], reservations: [] }; const solidCells = new Map<string, string>();
  for (const object of world.objects) { const definition = world.objectDefinitions[object.definitionId]; for (const offset of definition.footprint) { const cell = { x: object.origin.x + offset.x, y: object.origin.y + offset.y }; validateCell(cell, `object ${object.id} footprint`, world); if (!definition.blocksMovement) continue; const cellKey = `${cell.x},${cell.y}`; const previous = solidCells.get(cellKey); if (previous) fail(`solid objects ${previous} and ${object.id} overlap at ${cellKey}`); solidCells.set(cellKey, object.id); } for (const slot of definition.slots) { const cell = { x: object.origin.x + slot.offset.x, y: object.origin.y + slot.offset.y }; validateCell(cell, `slot ${object.id}:${slot.id}`, world); const query = queryCell(world, runtime, cell); if (!query.walkable) fail(`slot ${object.id}:${slot.id} is not clear at ${cell.x},${cell.y}: ${query.reason}`); } }
  const surfaceCells = new Set<string>(); for (const surface of world.surfaces) for (const cell of surface.cells) { const cellKey = `${cell.x},${cell.y}`; if (surfaceCells.has(cellKey)) fail(`movement surfaces overlap at ${cellKey}`); surfaceCells.add(cellKey); }
  const spawnCells = world.spawns.map(spawn => { const query = queryCell(world, runtime, spawn.cell); if (!query.walkable) fail(`spawn ${spawn.id} is not clear at ${spawn.cell.x},${spawn.cell.y}: ${query.reason}`); return spawn.cell; });
  const capabilityTargets = world.objects.flatMap(object => { const definition = world.objectDefinitions[object.definitionId]; return definition.capabilities.flatMap(capability => definition.slots.map(slot => ({ capability, cell: { x: object.origin.x + slot.offset.x, y: object.origin.y + slot.offset.y }, objectId: object.id, slotId: slot.id }))); });
  const reachable = reachableFromSpawns(world, runtime, spawnCells);
  for (const target of capabilityTargets) { if (!reachable.has(`${target.cell.x},${target.cell.y}`)) fail(`capability ${target.capability} at ${target.objectId}:${target.slotId} is unreachable from every spawn`); }
}
function reachableFromSpawns(world: DecodedWorldBundle, runtime: WorldRuntimeState, starts: Cell[]): Set<string> { const queue = starts.slice().sort((a, b) => a.y - b.y || a.x - b.x); const seen = new Set(queue.map(cell => `${cell.x},${cell.y}`)); let head = 0; while (head < queue.length) { const current = queue[head++]; for (const next of [{ x: current.x, y: current.y - 1 }, { x: current.x - 1, y: current.y }, { x: current.x + 1, y: current.y }, { x: current.x, y: current.y + 1 }]) { const key = `${next.x},${next.y}`; if (seen.has(key)) continue; const edge = canTraverse(world, runtime, current, next); if (!edge.walkable) continue; seen.add(key); queue.push(next); } } return seen; }
