import type { Cell, ObjectDefinition, WorldBundle, WorldRuntimeState } from "./types.js";
import { bundleHash } from "./canonical.js";
import { canTraverse, queryCell } from "./spatial.js";

const fail = (message: string): never => { throw new Error(message); };
function assert(condition: unknown, message: string): asserts condition { if (!condition) fail(message); }
function validateCell(cell: unknown, label: string, world: WorldBundle): asserts cell is Cell { assert(cell && typeof cell === "object", `${label} must be an object`); const c = cell as Cell; assert(Number.isInteger(c.x) && Number.isInteger(c.y), `${label} must use integer coordinates`); assert(c.x >= 0 && c.y >= 0 && c.x < world.width && c.y < world.height, `${label} is out of bounds at ${c.x},${c.y}`); }
function validateOffsets(offsets: Cell[], label: string) { const seen = new Set<string>(); for (const cell of offsets) { assert(Number.isInteger(cell.x) && Number.isInteger(cell.y), `${label} contains a non-integer offset`); const key = `${cell.x},${cell.y}`; assert(!seen.has(key), `${label} contains duplicate offset ${key}`); seen.add(key); } }
function validateDefinition(definition: ObjectDefinition) { assert(definition.id.length > 0, "object definition id is empty"); validateOffsets(definition.footprint, `${definition.id}.footprint`); const slots = new Set<string>(); for (const slot of definition.slots) { assert(slot.id.length > 0 && !slots.has(slot.id), `${definition.id} has duplicate slot id`); slots.add(slot.id); validateOffsets([slot.offset], `${definition.id}.${slot.id}`); } assert(Number.isInteger(definition.capacity) && definition.capacity >= 0 && definition.capacity <= Math.max(0, definition.slots.length), `${definition.id} has invalid capacity`); if (definition.capabilities.length === 0) assert(definition.capacity === 0, `${definition.id} has capacity without capabilities`); }
export function validateWorldBundle(world: WorldBundle): void {
  assert(world && typeof world === "object", "world bundle must be an object"); assert(world.schemaVersion === 2 && world.spatialModel === "structured-v2" && world.simulationVersion === "mimir-sim-v2", "unsupported world bundle version");
  assert(typeof world.id === "string" && world.id.length > 0, "world id is required"); assert(Number.isInteger(world.width) && world.width > 0 && Number.isInteger(world.height) && world.height > 0, "invalid world dimensions"); assert(world.cellSizePx === 24, "unsupported cell size");
  assert(world.terrain.length === world.height && world.terrain.every(row => row.length === world.width), "terrain dimensions do not match world"); for (const row of world.terrain) for (const id of row) assert(world.terrainDefinitions[id], `unknown terrain ${id}`); for (const terrain of Object.values(world.terrainDefinitions)) { if (!terrain.walkable) continue; const movementCost = terrain.movementCost; if (typeof movementCost !== "number" || !Number.isInteger(movementCost) || movementCost <= 0) fail(`terrain ${terrain.id} has invalid movement cost`); }
  const objectIds = new Set<string>(); for (const object of world.objects) { assert(object.id.length > 0 && !objectIds.has(object.id), `duplicate or empty object id ${object.id}`); objectIds.add(object.id); assert(object.definitionId in world.objectDefinitions, `unknown object definition ${object.definitionId}`); assert(object.orientation === 0, `unsupported orientation for ${object.id}`); validateCell(object.origin, `object ${object.id}`, world); }
  for (const definition of Object.values(world.objectDefinitions)) validateDefinition(definition); for (const surface of world.surfaces) { assert(Number.isInteger(surface.movementCost) && surface.movementCost > 0, `surface ${surface.id} has invalid movement cost`); for (const cell of surface.cells) validateCell(cell, `surface ${surface.id}`, world); }
  const spawnIds = new Set<string>(); for (const spawn of world.spawns) { assert(!spawnIds.has(spawn.id) && spawn.id.length > 0, `duplicate or empty spawn id ${spawn.id}`); spawnIds.add(spawn.id); validateCell(spawn.cell, `spawn ${spawn.id}`, world); }
  assert(world.bundle?.schemaVersion === 2 && world.bundle.contentHash === bundleHash(world), "world bundle content hash does not match definition");
  validateAuthoredSpatialContent(world);
}
export function validateRuntimeState(world: WorldBundle, runtime: WorldRuntimeState): void { assert(Number.isInteger(runtime.navigationRevision) && runtime.navigationRevision >= 0, "invalid navigation revision"); const objects = new Set(world.objects.map(o => o.id)); const slots = new Set(world.objects.flatMap(o => (world.objectDefinitions[o.definitionId]?.slots ?? []).map(s => `${o.id}:${s.id}`))); const seen = new Set<string>(); for (const state of runtime.objects) assert(objects.has(state.objectId), `runtime references unknown object ${state.objectId}`); for (const reservation of runtime.reservations) { const key = `${reservation.objectId}:${reservation.slotId}`; assert(slots.has(key), `runtime references unknown slot ${key}`); assert(!seen.has(key), `duplicate reservation ${key}`); seen.add(key); } }

export function validateAuthoredSpatialContent(world: WorldBundle): void {
  const runtime: WorldRuntimeState = { navigationRevision: 0, objects: [], reservations: [] }; const solidCells = new Map<string, string>();
  for (const object of world.objects) { const definition = world.objectDefinitions[object.definitionId]; for (const offset of definition.footprint) { const cell = { x: object.origin.x + offset.x, y: object.origin.y + offset.y }; validateCell(cell, `object ${object.id} footprint`, world); if (!definition.blocksMovement) continue; const cellKey = `${cell.x},${cell.y}`; const previous = solidCells.get(cellKey); if (previous) fail(`solid objects ${previous} and ${object.id} overlap at ${cellKey}`); solidCells.set(cellKey, object.id); } for (const slot of definition.slots) { const cell = { x: object.origin.x + slot.offset.x, y: object.origin.y + slot.offset.y }; validateCell(cell, `slot ${object.id}:${slot.id}`, world); const query = queryCell(world, runtime, cell); if (!query.walkable) fail(`slot ${object.id}:${slot.id} is not clear at ${cell.x},${cell.y}: ${query.reason}`); } }
  const surfaceCells = new Set<string>(); for (const surface of world.surfaces) for (const cell of surface.cells) { const cellKey = `${cell.x},${cell.y}`; if (surfaceCells.has(cellKey)) fail(`movement surfaces overlap at ${cellKey}`); surfaceCells.add(cellKey); }
  const spawnCells = world.spawns.map(spawn => { const query = queryCell(world, runtime, spawn.cell); if (!query.walkable) fail(`spawn ${spawn.id} is not clear at ${spawn.cell.x},${spawn.cell.y}: ${query.reason}`); return spawn.cell; });
  const capabilityTargets = world.objects.flatMap(object => { const definition = world.objectDefinitions[object.definitionId]; return definition.capabilities.flatMap(capability => definition.slots.map(slot => ({ capability, cell: { x: object.origin.x + slot.offset.x, y: object.origin.y + slot.offset.y }, objectId: object.id, slotId: slot.id }))); });
  for (const target of capabilityTargets) { if (!spawnCells.some(spawn => canReach(world, runtime, spawn, target.cell))) fail(`capability ${target.capability} at ${target.objectId}:${target.slotId} is unreachable from every spawn`); }
}
function canReach(world: WorldBundle, runtime: WorldRuntimeState, start: Cell, goal: Cell): boolean { const queue = [start]; const seen = new Set([`${start.x},${start.y}`]); while (queue.length) { const current = queue.shift()!; if (current.x === goal.x && current.y === goal.y) return true; for (const next of [{ x: current.x, y: current.y - 1 }, { x: current.x - 1, y: current.y }, { x: current.x + 1, y: current.y }, { x: current.x, y: current.y + 1 }]) { const key = `${next.x},${next.y}`; if (seen.has(key)) continue; const edge = canTraverse(world, runtime, current, next); if (!edge.walkable) continue; seen.add(key); queue.push(next); } } return false; }
