import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const path = resolve(process.cwd(), process.env.MIMIR_AI_P13_REPORT ?? ".tmp/ai-p13-hybrid-pilot.json");
assert.equal(existsSync(path), true, `missing pilot report: ${path}`);
const report = JSON.parse(readFileSync(path, "utf8"));
assert.equal(report.fixedSeed, 20260912);
assert.equal(report.encounters, 32);
assert.equal(report.budgets.perSparkDailyLimit, 4);
assert.equal(report.budgets.globalDailyLimit, 16);
assert.equal(report.budgets.withinCaps, true);
assert.equal(report.acceptance.isolated, true);
assert.equal(report.acceptance.deterministicAuthority, true);
assert.equal(report.acceptance.replayProviderFree, true);
assert.equal(report.acceptance.noBroaderDeployment, true);
assert.equal(report.replay.providerCalls, 0);
assert.equal(report.replay.budgetUnitsUsed, 0);
assert.equal(report.stateDiffs.length, 32);
console.log("AI-P13 pilot evidence checks passed");
