import { readFileSync, mkdirSync, writeFileSync, existsSync, copyFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, resolve, join } from "node:path";
import { bundleHash, validateWorldBundle } from "@mimir/world-data";

const source = resolve(process.argv[2] ?? "assets/world/maps/first-glow.tiled.json");
const outputRoot = resolve(process.env.WORLD_BUNDLE_ROOT ?? "assets/world/generated");
const map = JSON.parse(readFileSync(source, "utf8"));
const property = (name) => Array.isArray(map.properties) ? map.properties.find(item => item.name === name)?.value : map[name];
if (property("themeId") === "living-circuit" || property("ageId") === "first-glow") {
  if (map.orientation !== "orthogonal" || map.infinite || map.tilewidth !== 24 || map.tileheight !== 24) throw new Error(`${source}: First Glow requires a finite orthogonal 24px map`);
  if (property("themeId") !== "living-circuit" || property("ageId") !== "first-glow" || property("simulationVersion") !== "mimir-sim-v3-first-glow") throw new Error(`${source}: incomplete First Glow theme metadata`);
  const sourceRoot = dirname(source);
  const tileset = map.tilesets?.find(item => item.source);
  if (!tileset || tileset.firstgid !== 1) throw new Error(`${source}: an external tileset with firstgid 1 is required`);
  const tilesetPath = resolve(sourceRoot, tileset.source);
  if (!existsSync(tilesetPath)) throw new Error(`${source}: missing external tileset ${tileset.source}`);
  const tilesetData = JSON.parse(readFileSync(tilesetPath, "utf8"));
  if (tilesetData.tilewidth !== 24 || tilesetData.tileheight !== 24 || !Array.isArray(tilesetData.tiles)) throw new Error(`${tilesetPath}: malformed First Glow tileset`);
  const layer = (role, type) => map.layers?.find(item => item.role === role && item.type === type);
  const groundLayer = layer("ground", "tilelayer"); const surfaceLayer = layer("surface", "tilelayer"); const objectLayer = layer("objects", "objectgroup"); const spawnLayer = layer("spawns", "objectgroup");
  if (!groundLayer || !surfaceLayer || !objectLayer || !spawnLayer) throw new Error(`${source}: required role layers are missing`);
  if (groundLayer.data.length !== map.width * map.height || surfaceLayer.data.length !== map.width * map.height) throw new Error(`${source}: tile layer data is incomplete`);
  const terrain = Array.from({ length: map.height }, (_, y) => Array.from({ length: map.width }, (_, x) => { const gid = groundLayer.data[y * map.width + x]; if (gid === 1) return "open"; if (gid === 2) return "gap"; throw new Error(`${source}: unsupported ground GID ${gid} at ${x},${y}`); }));
  const traceCells = []; for (let y = 0; y < map.height; y += 1) for (let x = 0; x < map.width; x += 1) if (surfaceLayer.data[y * map.width + x] === 3) traceCells.push({ x, y });
  const templates = new Map(); const objectDefinitions = {};
  for (const item of objectLayer.objects) {
    if (typeof item.template !== "string") throw new Error(`${source}: object ${item.id} must reference a template`);
    if (item.rotation || item.gid && item.gid < 0 || item.flippedHorizontally || item.flippedVertically) throw new Error(`${source}: unsupported transform on object ${item.id}`);
    const templatePath = resolve(sourceRoot, item.template); if (!templatePath.startsWith(resolve(sourceRoot, ".."))) throw new Error(`${source}: template escapes source root`); if (!existsSync(templatePath)) throw new Error(`${source}: missing template ${item.template}`);
    const template = JSON.parse(readFileSync(templatePath, "utf8")); if (!template.id || !Array.isArray(template.footprint) || !Array.isArray(template.slots) || !Array.isArray(template.capabilities)) throw new Error(`${templatePath}: malformed template`);
    if (templates.has(template.id) && JSON.stringify(templates.get(template.id)) !== JSON.stringify(template)) throw new Error(`${source}: conflicting template ${template.id}`); templates.set(template.id, template); objectDefinitions[template.id] = structuredClone(template);
  }
  const assets = []; const assetSources = new Map(); for (const definition of Object.values(objectDefinitions)) { const assetName = definition.visualAsset; if (typeof assetName !== "string") throw new Error(`template ${definition.id}: visualAsset is required`); const assetPath = resolve(sourceRoot, "..", "assets", assetName); if (!existsSync(assetPath)) throw new Error(`${source}: missing asset ${assetName}`); const digest = createHash("sha256").update(readFileSync(assetPath)).digest("hex"); const outputName = `assets/${digest}-${assetName}`; definition.visualAsset = outputName; assets.push({ path: outputName, sha256: `sha256-${digest}`, mediaType: "image/svg+xml", version: property("assetVersion") ?? "first-glow-v1", provenance: "assets/licenses/first-glow-assets.md" }); assetSources.set(outputName, assetPath); }
  const objects = objectLayer.objects.map(item => { const definitionId = JSON.parse(readFileSync(resolve(sourceRoot, item.template), "utf8")).id; if (item.x % 24 || item.y % 24) throw new Error(`${source}: object ${item.id} is not grid aligned`); return { id: `tiled-${item.id}`, definitionId, origin: { x: item.x / 24, y: item.y / 24 }, orientation: 0 }; });
  const relay = objects.find(item => item.definitionId === "relay-crossing"); const surfaces = [{ id: "trace-main", cells: traceCells, movementCost: 1, enabled: true, visualAsset: assets.find(asset => asset.path.includes("trace"))?.path }]; if (relay) surfaces.push({ id: `${relay.id}-surface`, cells: [{ x: relay.origin.x, y: relay.origin.y }, { x: relay.origin.x + 1, y: relay.origin.y }, { x: relay.origin.x + 2, y: relay.origin.y }], movementCost: 1, enabled: true, visualAsset: objectDefinitions[relay.definitionId].visualAsset });
  const spawns = spawnLayer.objects.map(item => { if (item.x % 24 || item.y % 24) throw new Error(`${source}: spawn ${item.id} is not grid aligned`); return { id: item.name || `spawn-${item.id}`, cell: { x: item.x / 24, y: item.y / 24 }, settlementId: "first-glow-region", entrance: Boolean(item.entrance) }; });
  const world = { schemaVersion: 3, spatialModel: "structured-v2", simulationVersion: "mimir-sim-v3-first-glow", themeId: "living-circuit", ageId: "first-glow", id: property("bundleId") ?? "first-glow-v1", width: map.width, height: map.height, cellSizePx: 24, terrain, terrainDefinitions: { open: { id: "open", label: "Open space", walkable: true, movementCost: 2, visualAsset: "" }, gap: { id: "gap", label: "Circuit gap", walkable: false, visualAsset: "" } }, surfaces, objectDefinitions, objects, layers: map.layers.filter(item => item.role).map(item => ({ id: String(item.id), role: item.role, order: item.id })), spawns, assets, bundle: { bundleId: property("bundleId") ?? "first-glow-v1", contentHash: "", schemaVersion: 3, assetVersion: property("assetVersion") ?? "first-glow-v1" } };
  world.bundle.contentHash = bundleHash(world); validateWorldBundle(world); const destination = join(outputRoot, world.bundle.contentHash); mkdirSync(join(destination, "assets"), { recursive: true }); const bundlePath = join(destination, "world.json"); const bytes = JSON.stringify(world, null, 2) + "\n"; if (existsSync(bundlePath) && readFileSync(bundlePath, "utf8") !== bytes) throw new Error(`immutable bundle collision at ${bundlePath}`); writeFileSync(bundlePath, bytes); for (const [outputName, assetPath] of assetSources) { const target = join(destination, outputName); if (existsSync(target) && readFileSync(target).compare(readFileSync(assetPath)) !== 0) throw new Error(`immutable asset collision at ${target}`); if (!existsSync(target)) copyFileSync(assetPath, target); } writeFileSync(join(destination, "manifest.json"), JSON.stringify({ bundle: world.bundle, source, generatedAt: "source-independent", assets }, null, 2) + "\n"); console.log(JSON.stringify({ source, bundle: world.bundle, path: bundlePath, assets: assets.length }, null, 2)); process.exit(0);
}
throw new Error(`${source}: only First Glow schema-3 sources are supported`);
if (map.orientation !== "orthogonal" || map.infinite || map.tilewidth !== 24 || map.tileheight !== 24) throw new Error(`${source}: only finite orthogonal 24px maps are supported`);
const terrainLayer = map.layers.find(layer => layer.type === "tilelayer" && layer.name === "Terrain");
if (!terrainLayer || terrainLayer.data.length !== map.width * map.height) throw new Error(`${source}: named Terrain layer is missing or incomplete`);
const terrain = Array.from({ length: map.height }, (_, y) => Array.from({ length: map.width }, (_, x) => ({ 1: "grass", 2: "water", 3: "road" }[terrainLayer.data[y * map.width + x]] ?? (() => { throw new Error(`${source}: unsupported terrain GID ${terrainLayer.data[y * map.width + x]}`); })())));
const slots = (prefix, offsets) => offsets.map((offset, index) => ({ id: `${prefix}-${index + 1}`, offset, capacity: 1 }));
const objectDefinitions = {
  house: { id: "house", footprint: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }], slots: slots("rest", [{ x: 0, y: 2 }, { x: 1, y: 2 }]), capabilities: ["rest"], capacity: 2, visualAsset: "provisional/house", groundContact: { x: 24, y: 48 }, blocksMovement: true },
  tree: { id: "tree", footprint: [{ x: 0, y: 0 }], slots: slots("gather", [{ x: 0, y: 1 }]), capabilities: ["gather"], capacity: 1, visualAsset: "provisional/tree", groundContact: { x: 12, y: 24 }, blocksMovement: true, foreground: true },
  granary: { id: "granary", footprint: [{ x: 0, y: 0 }, { x: 1, y: 0 }], slots: slots("food", [{ x: 0, y: 1 }, { x: 1, y: 1 }]), capabilities: ["collect", "share"], capacity: 2, visualAsset: "provisional/granary", groundContact: { x: 24, y: 24 }, blocksMovement: true },
  bridge: { id: "bridge", footprint: [], slots: [], capabilities: [], capacity: 0, visualAsset: "provisional/bridge", groundContact: { x: 36, y: 24 }, blocksMovement: false },
  workshop: { id: "workshop", footprint: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }], slots: slots("craft", [{ x: 0, y: 2 }, { x: 1, y: 2 }]), capabilities: ["craft"], capacity: 2, visualAsset: "provisional/workshop", groundContact: { x: 24, y: 48 }, blocksMovement: true },
  field: { id: "field", footprint: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 1 }], slots: slots("work", [{ x: 1, y: 2 }]), capabilities: ["work"], capacity: 1, visualAsset: "provisional/field", groundContact: { x: 36, y: 48 }, blocksMovement: false },
  "meeting-hall": { id: "meeting-hall", footprint: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }], slots: slots("meet", [{ x: 0, y: 2 }, { x: 1, y: 2 }]), capabilities: ["meet"], capacity: 2, visualAsset: "provisional/meeting-hall", groundContact: { x: 24, y: 48 }, blocksMovement: true }
};
const objectLayer = map.layers.find(layer => layer.type === "objectgroup" && layer.name === "Objects");
if (!objectLayer) throw new Error(`${source}: named Objects layer is missing`);
const objects = objectLayer.objects.map(object => { const definitionId = String(object.class ?? object.type ?? ""); if (!(definitionId in objectDefinitions)) throw new Error(`${source}: object ${object.id} has unsupported class ${definitionId}`); if (object.x % 24 || object.y % 24) throw new Error(`${source}: object ${object.id} is not grid aligned`); return { id: `tiled-${object.id}`, definitionId, origin: { x: object.x / 24, y: object.y / 24 }, orientation: 0 }; });
const bridge = objects.find(object => object.definitionId === "bridge");
const surfaces = bridge ? [{ id: `${bridge.id}-surface`, cells: [{ x: bridge.origin.x, y: bridge.origin.y }, { x: bridge.origin.x + 1, y: bridge.origin.y }, { x: bridge.origin.x + 2, y: bridge.origin.y }], movementCost: 1, enabled: true, visualAsset: "provisional/bridge" }] : [];
const world = { schemaVersion: 2, spatialModel: "structured-v2", simulationVersion: "mimir-sim-v2", id: "first-winter-v2", width: map.width, height: map.height, cellSizePx: 24, terrain, terrainDefinitions: { grass: { id: "grass", walkable: true, movementCost: 2, visualAsset: "provisional/grass" }, road: { id: "road", walkable: true, movementCost: 1, visualAsset: "provisional/road" }, water: { id: "water", walkable: false, visualAsset: "provisional/water" } }, surfaces, objectDefinitions, objects, layers: [{ id: "terrain", role: "ground", order: 0 }, { id: "surfaces", role: "surface", order: 1 }, { id: "objects", role: "objects", order: 2 }, { id: "foreground", role: "foreground", order: 3 }, { id: "spawns", role: "spawns", order: 4 }], spawns: [{ id: "home-spawn-1", cell: { x: 0, y: 0 }, settlementId: "first-village", entrance: true }, { id: "home-spawn-2", cell: { x: 3, y: 0 }, settlementId: "first-village" }, { id: "home-spawn-3", cell: { x: 5, y: 0 }, settlementId: "first-village" }, { id: "home-spawn-4", cell: { x: 0, y: 3 }, settlementId: "first-village" }, { id: "home-spawn-5", cell: { x: 3, y: 3 }, settlementId: "first-village" }, { id: "home-spawn-6", cell: { x: 7, y: 3 }, settlementId: "first-village" }, { id: "home-spawn-7", cell: { x: 0, y: 4 }, settlementId: "first-village" }, { id: "home-spawn-8", cell: { x: 3, y: 4 }, settlementId: "first-village" }, { id: "home-spawn-9", cell: { x: 7, y: 4 }, settlementId: "first-village" }, { id: "home-spawn-10", cell: { x: 0, y: 7 }, settlementId: "first-village" }, { id: "home-spawn-11", cell: { x: 5, y: 7 }, settlementId: "first-village" }, { id: "home-spawn-12", cell: { x: 7, y: 7 }, settlementId: "first-village" }, { id: "riverbend-entrance", cell: { x: 7, y: 7 }, settlementId: "riverbend", entrance: true }], assets: [], bundle: { bundleId: "first-winter-v2", contentHash: "", schemaVersion: 2, assetVersion: "provisional-v1" } };
world.bundle.contentHash = bundleHash(world); validateWorldBundle(world);
const destination = join(outputRoot, world.bundle.contentHash); mkdirSync(destination, { recursive: true }); const bundlePath = join(destination, "world.json"); const bytes = JSON.stringify(world, null, 2) + "\n"; if (existsSync(bundlePath) && readFileSync(bundlePath, "utf8") !== bytes) throw new Error(`immutable bundle collision at ${bundlePath}`); writeFileSync(bundlePath, bytes); writeFileSync(join(destination, "manifest.json"), JSON.stringify({ bundle: world.bundle, source, generatedAt: "source-independent" }, null, 2) + "\n"); console.log(JSON.stringify({ source, bundle: world.bundle, path: bundlePath }, null, 2));
